# -*- coding: utf-8 -*-
"""
| ==============================================
|
|   Copyright (c) 2025 Nuoyan
|
|   Author: Nuoyan
|   Email : 1279735247@qq.com
|   Gitee : https://gitee.com/charming-lee
|   Date  : 2025-06-10
|
| ==============================================
"""


from types import MethodType, FunctionType
from typing import Tuple, TypeVar, Callable, Union, Any, Type, Optional, Dict
from ._types._typing import ITuple


_T = TypeVar("_T")
_T_CO = TypeVar("_T_CO", bound=CachedObject)


def get_func(cls: type, module: ITuple, func: ITuple) -> FunctionType: ...
def assert_error(func: Callable, args: tuple, *error: Exception) -> None: ...


class cached_property(object):
    __doc__: Optional[str]
    getter: Callable[[Any], Any]
    def __init__(self, getter: Callable[[Any], Any]) -> None: ...
    def __get__(self, ins: Any, cls: type) -> Any: ...


def join_chr(*seq: int) -> str: ...


class _CachedObjectMeta(type):
    def __new__(metacls, name: str, bases: Tuple[type, ...], dct: Dict[str, Any]) -> _CachedObjectMeta: ...


class CachedObject(metaclass=_CachedObjectMeta):
    __cache__: Dict[tuple, CachedObject]
    def __new__(cls: Type[_T_CO], *args: Any, **kwargs: Any) -> _T_CO: ...
    @classmethod
    def __cache_key__(cls, *args: Any, **kwargs: Any) -> tuple: ...


def hook_method(ins: Any, org_method_name: str, my_method: MethodType) -> None: ...
def args_type_check(*typ: Union[type, Tuple[type, ...]], is_method: bool = False) -> Callable[[_T], _T]: ...
def cached_method(method: _T) -> _T: ...
def cached_func(func: _T) -> _T: ...
def singleton(init_once: Union[bool, type] = True) -> Union[Callable[[type], type], type]: ...
def is_inv36_key(k: str) -> bool: ...
def is_inv27_key(k: str) -> bool: ...
def is_shortcut_key(k: str) -> bool: ...
def is_inv_key(k: str) -> bool: ...
def is_not_inv_key(k: str) -> bool: ...
