# -*- coding: utf-8 -*-
#  ================================================
#  ⠀
#    Copyright (c) 2026 Nuoyan
#  ⠀
#    Author: Nuoyan <https://github.com/charminglee>
#    Email : 1279735247@qq.com
#    Date  : 2026-9-12
#  ⠀
#  ================================================


from typing import Tuple


class ControlTypeNotMatchedError(RuntimeError):
    t_name: str
    path: str
    def __init__(self, t: int, path: str) -> None: ...
    def __str__(self) -> str: ...
class ControlAlreadyExistsError(RuntimeError):
    path: str
    def __init__(self, path: str) -> None: ...
    def __str__(self) -> str: ...
class ControlNotFoundError(RuntimeError):
    path: str
    def __init__(self, path: str) -> None: ...
    def __str__(self) -> str: ...
class SystemNotFoundError(RuntimeError):
    ns: str
    sys_name: str
    def __init__(self, ns: str, sys_name: str) -> None: ...
    def __str__(self) -> str: ...
class NuoyanLibServerSystemRegisterError(RuntimeError):
    pass
class NuoyanLibClientSystemRegisterError(RuntimeError):
    pass
class PathMatchError(RuntimeError):
    pattern: str
    def __init__(self, pattern: str) -> None: ...
    def __str__(self) -> str: ...
class AcrossImportError(ImportError):
    def __str__(self) -> str: ...
class GetPropertyError(AttributeError):
    name: str
    def __init__(self, name: str) -> None: ...
    def __str__(self) -> str: ...
class ScreenNodeNotFoundError(RuntimeError):
    def __str__(self) -> str: ...
class EventParameterError(AttributeError):
    event_id: str
    param: str
    def __init__(self, event_id: str, param: str) -> None: ...
    def __str__(self) -> str: ...
class VectorError(Exception): ...
class EventSourceError(TypeError):
    args = Tuple[str, str, str]
    def __init__(self, name: str, ns: str, sys_name: str) -> None: ...
    def __str__(self) -> str: ...
class EventNotFoundError(AttributeError):
    name: str
    is_client: bool
    def __init__(self, name: str, is_client: bool) -> None: ...
    def __str__(self) -> str: ...
