# -*- coding: utf-8 -*-
"""
| ==============================================
|
|   Copyright (c) 2025 Nuoyan
|
|   Author: Nuoyan
|   Email : 1279735247@qq.com
|   Gitee : https://gitee.com/charming-lee
|   Date  : 2025-06-06
|
| ==============================================
"""


from mod.common.minecraftEnum import EntityType


__all__ = [
    "Enum",
    "search_data",
    "ITEM_LIST",
    "BLOCK_LIST",
    "STRUCTURE_DICT",
    "BIOME_DICT",
    "EFFECT_DICT",
    "ENTITY_ID_DICT",
    "ATTACKABLE_MOB_LIST",
    "HOSTILE_MOB_LIST",
    "FRIENDLY_MOB_LIST",
    "MOB_LIST",
    "ENTITY_LIST",
]


class EnumMeta(type):
    def __new__(metacls, name, bases, dct, restrict_type=None):
        dct['__flag__'] = 0
        cls = type.__new__(metacls, name, bases, dct) # type: type[Enum]
        members = {}
        if name != "Enum":
            # 遍历当前Enum成员
            for k, v in dct.items():
                if k.startswith("_"):
                    continue
                if isinstance(v, Enum.auto):
                    member = cls.__gen_auto_value__(k) # NOQA
                elif cls._restrict_type:
                    if type(v) is not cls._restrict_type:
                        raise TypeError(
                            "member of '%s' must be '%s', not '%s'"
                            % (name, cls._restrict_type.__name__, type(v).__name__)
                        )
                    member = v
                else:
                    member = cls(k, v) # type: Enum
                members[k] = member
                setattr(cls, k, member)
            # 继承父Enum成员
            for base in bases:
                if isinstance(base, EnumMeta):
                    members.update(base.__members__)
        else:
            cls._restrict_type = restrict_type
        cls.__members__ = members
        cls.__flag__ = 1
        return cls

    def __setattr__(cls, name, value):
        # 禁止动态设置枚举值
        if getattr(cls, '__flag__', 0) == 1:
            raise AttributeError("can't set member '%s' in '%s'" % (name, cls.__name__))
        type.__setattr__(cls, name, value)

    def __delattr__(cls, name):
        # 禁止删除枚举值
        raise AttributeError("can't delete member '%s' in '%s'" % (name, cls.__name__))

    def __contains__(cls, member):
        # 支持in
        for v in cls.__members__.values():
            if cls._restrict_type:
                if v == member:
                    return True
            elif v.value == member:
                return True
        return False

    def __len__(cls):
        # 支持len()
        return len(cls.__members__)

    def __iter__(cls):
        # 支持遍历
        return iter(cls.__members__.values())

    def __getitem__(cls, item):
        # 支持Enum[type]/Enum['xxx']
        if cls is Enum:
            dct = dict(Enum.__dict__)
            del dct['__dict__']
            del dct['__weakref__']
            del dct['__members__']
            del dct['__flag__']
            new_cls = EnumMeta.__new__(EnumMeta, "Enum", (object,), dct, item)
            return new_cls
        else:
            return cls.__members__[item]

    def __gen_auto_value__(cls, name=None):
        t = getattr(cls, '_restrict_type', None)
        if t is str:
            val = name
        elif t is int:
            val = getattr(cls, '_last_auto_value', -1) + 1
            cls._last_auto_value = val
        else:
            raise TypeError("unsupported type '%s'" % t.__name__)
        return val


class Enum(object):
    """
    | 枚举类型，用于实现自定义枚举值。
    | 支持以下功能：
    - ``len()``: 获取枚举值数量
    - 通过for循环等方式进行遍历
    - 通过 ``in`` 关键字判断某个值是否在枚举范围内
    - 可通过 ``Enum[type]`` 的方式定义特定类型的枚举值，如 ``Enum[int]`` 定义int类型枚举值
    - 可通过 ``MyEnum.xxx`` 或 ``MyEnum['xxx']`` 的方式获取指定枚举值
    | 注意事项：
    - 枚举值是无序的（类似于字典），因此遍历顺序与编写顺序无关
    - 不支持动态插入或删除枚举值
    - 枚举名不能以下划线开头
    """

    __metaclass__ = EnumMeta

    class auto(object):
        pass

    def __init__(self, name, value):
        self.__name = name
        self.__value = value
        self.__hash = hash(name)

    def __repr__(self):
        return "<%s.%s: %s>" % (self.__class__.__name__, self.__name, repr(self.__value))

    def __hash__(self):
        return self.__hash

    @property
    def name(self):
        return self.__name

    @property
    def value(self):
        return self.__value


def __test__():
    class E(Enum[str]):
        a = Enum.auto()
        b = Enum.auto()
        c = Enum.auto()
    class T(E):
        d = Enum.auto()
        e = Enum.auto()
    assert E.a == "a"
    assert T.a == "a"
    assert T.d == "d"

    class E1(Enum):
        A = 1
        B = 2
        C = 3
    class E2(E1):
        X = 7
        Y = 8
        Z = 9
    assert sorted(E2.__members__.keys()) == ["A", "B", "C", "X", "Y", "Z"]
    assert 7 in E2
    assert 0 not in E2
    assert len(E2) == 6
    assert isinstance(E2.X, E2)
    assert E2.A.name == "A"
    assert E2.A.value == 1
    a = {E2.A, E2.X}
    assert E2.A in a
    assert E2.X in a

    class E3(Enum[str]):
        Q = "114514"
    assert E3.Q == "114514"
    from .._core._utils import assert_error
    def f():
        E3.Q = 123
    assert_error(f, (), AttributeError)
    def f():
        del E3.Q
    assert_error(f, (), AttributeError)

    class E4(Enum[int]):
        a = Enum.auto()
        b = Enum.auto()
        c = Enum.auto()
    assert sorted(E4.__members__.values()) == [0, 1, 2]


def search_data(data, lst):
    """
    | 在列表中搜索数据。

    -----

    :param Any data: 数据（实体数字id、类型id等）
    :param list lst: 待检测列表（ENTITY_LIST、MOB_LIST等）

    :return: 若数据在列表中则返回True，否则返回False
    :rtype: bool
    """
    if data in lst:
        return True
    for i in lst:
        if i and isinstance(i, list) and data in i:
            return True
    return False


# 实体列表
# 数字ID，中文名，英文ID，网易版ID
ENTITY_LIST = [
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    None,
    (10, "鸡", "chicken", EntityType.Chicken),
    (11, "牛", "cow", EntityType.Cow),
    (12, "猪", "pig", EntityType.Pig),
    (13, "羊", "sheep", EntityType.Sheep),
    (14, "狼", "wolf", EntityType.Wolf),
    (15, "村民", "villager", EntityType.Villager),
    (16, "哞菇", "mooshroom", EntityType.MushroomCow),
    (17, "鱿鱼", "squid", EntityType.Squid),
    (18, "兔子", "rabbit", EntityType.Rabbit),
    (19, "蝙蝠", "bat", EntityType.Bat),
    (20, "铁傀儡", "iron_golem", EntityType.IronGolem),
    (21, "雪傀儡", "snow_golem", EntityType.SnowGolem),
    (22, "豹猫", "ocelot", EntityType.Ocelot),
    (23, "马", "horse", EntityType.Horse),
    (24, "驴", "donkey", EntityType.Donkey),
    (25, "骡", "mule", EntityType.Mule),
    (26, "骷髅马", "skeleton_horse", EntityType.SkeletonHorse),
    (27, "僵尸马", "zombie_horse", EntityType.ZombieHorse),
    (28, "北极熊", "polar_bear", EntityType.PolarBear),
    (29, "羊驼", "llama", EntityType.Llama),
    (30, "鹦鹉", "parrot", EntityType.Parrot),
    (31, "海豚", "dolphin", EntityType.Dolphin),
    (32, "僵尸", "zombie", EntityType.Zombie),
    (33, "苦力怕", "creeper", EntityType.Creeper),
    (34, "骷髅", "skeleton", EntityType.Skeleton),
    (35, "蜘蛛", "spider", EntityType.Spider),
    (36, "僵尸猪灵", "zombie_pigman", EntityType.PigZombie),
    (37, "史莱姆", "slime", EntityType.Slime),
    (38, "末影人", "enderman", EntityType.EnderMan),
    (39, "蠹虫", "silverfish", EntityType.Silverfish),
    (40, "洞穴蜘蛛", "cave_spider", EntityType.CaveSpider),
    (41, "恶魂", "ghast", EntityType.Ghast),
    (42, "岩浆怪", "magma_cube", EntityType.LavaSlime),
    (43, "烈焰人", "blaze", EntityType.Blaze),
    (44, "僵尸村民", "zombie_villager", EntityType.ZombieVillager),
    (45, "女巫", "witch", EntityType.Witch),
    (46, "流浪者", "stray", EntityType.Stray),
    (47, "尸壳", "husk", EntityType.Husk),
    (48, "凋灵骷髅", "wither_skeleton", EntityType.WitherSkeleton),
    (49, "守卫者", "guardian", EntityType.Guardian),
    (50, "远古守卫者", "elder_guardian", EntityType.ElderGuardian),
    (51, "NPC", "npc", EntityType.Npc),
    (52, "凋灵", "wither", EntityType.WitherBoss),
    (53, "末影龙", "ender_dragon", EntityType.Dragon),
    (54, "潜影贝", "shulker", EntityType.Shulker),
    (55, "末影螨", "endermite", EntityType.Endermite),
    (56, "吉祥物", "agent", EntityType.Agent),
    (57, "卫道士", "vindicator", EntityType.Vindicator),
    (58, "幻翼", "phantom", EntityType.Phantom),
    (59, "劫掠兽", "ravager", EntityType.IllagerBeast),
    (60, "未知实体", "unknown", 0),
    (61, "盔甲架", "armor_stand", EntityType.ArmorStand),
    (62, "三脚架摄像机", "camera", EntityType.TripodCamera),
    (63, "玩家", "player", EntityType.Player),
    (64, "掉落物", "item", EntityType.ItemEntity),
    (65, "点燃的TNT", "tnt", EntityType.PrimedTnt),
    (66, "掉落的方块", "falling_block", EntityType.FallingBlock),
    (67, "移动的方块", "moving_block", EntityType.MovingBlock),
    (68, "扔出的附魔之瓶", "xp_bottle", EntityType.ExperiencePotion),
    (69, "经验球", "xp_orb", EntityType.Experience),
    (70, "扔出的末影之眼", "eye_of_ender_signal", EntityType.EyeOfEnder),
    (71, "末影水晶", "ender_crystal", EntityType.EnderCrystal),
    (72, "烟花火箭", "fireworks_rocket", EntityType.FireworksRocket),
    (73, "扔出的三叉戟", "thrown_trident", EntityType.Trident),
    (74, "海龟", "turtle", EntityType.Turtle),
    (75, "猫", "cat", EntityType.Cat),
    (76, "潜影贝导弹", "shulker_bullet", EntityType.ShulkerBullet),
    (77, "鱼钩浮漂", "fishing_hook", EntityType.FishingHook),
    (78, "黑板", "chalkboard", EntityType.Chalkboard),
    (79, "末影龙火球", "dragon_fireball", EntityType.DragonFireball),
    (80, "射出的箭", "arrow", EntityType.Arrow),
    (81, "扔出的雪球", "snowball", EntityType.Snowball),
    (82, "扔出的鸡蛋", "egg", EntityType.ThrownEgg),
    (83, "画", "painting", EntityType.Painting),
    (84, "矿车", "minecart", EntityType.Minecart),
    (85, "恶魂火球", "fireball", EntityType.LargeFireball),
    (86, "扔出的喷溅药水", "splash_potion", EntityType.ThrownPotion),
    (87, "扔出的末影珍珠", "ender_pearl", EntityType.Enderpearl),
    (88, "栓绳结", "leash_knot", EntityType.LeashKnot),
    (89, "黑色凋灵之首", "wither_skull", EntityType.WitherSkull),
    (90, "船", "boat", EntityType.BoatRideable),
    (91, "蓝色凋灵之首", "wither_skull_dangerous", EntityType.WitherSkullDangerous),
    None,
    (93, "闪电", "lightning_bolt", EntityType.LightningBolt),
    (94, "烈焰人火球", "small_fireball", EntityType.SmallFireball),
    (95, "区域效果云", "area_effect_cloud", EntityType.AreaEffectCloud),
    (96, "漏斗矿车", "hopper_minecart", EntityType.MinecartHopper),
    (97, "TNT矿车", "tnt_minecart", EntityType.MinecartTNT),
    (98, "运输矿车", "chest_minecart", EntityType.MinecartChest),
    None,
    (100, "命令方块矿车", "command_block_minecart", EntityType.MinecartCommandBlock),
    (101, "扔出的滞留药水", "lingering_potion", EntityType.LingeringPotion),
    (102, "羊驼唾沫", "llama_spit", EntityType.LlamaSpit),
    (103, "尖牙", "evocation_fang", EntityType.EvocationFang),
    (104, "唤魔者", "evocation_illager", EntityType.EvocationIllager),
    (105, "恼鬼", "vex", EntityType.Vex),
    (106, "冰弹", "ice_bomb", EntityType.IceBomb),
    (107, "气球", "balloon", EntityType.Balloon),
    (108, "河豚", "pufferfish", EntityType.Pufferfish),
    (109, "鲑鱼", "salmon", EntityType.Salmon),
    (110, "溺尸", "drowned", EntityType.Drowned),
    (111, "热带鱼", "tropicalfish", EntityType.Tropicalfish),
    (112, "鳕鱼", "cod", EntityType.Fish),
    (113, "熊猫", "panda", EntityType.Panda),
    (114, "掠夺者", "pillager", EntityType.Pillager),
    (115, "村民", "villager_v2", EntityType.VillagerV2),
    (116, "僵尸村民", "zombie_villager_v2", EntityType.ZombieVillagerV2),
    (117, "盾牌", "shield", EntityType.Shield),
    (118, "流浪商人", "wandering_trader", EntityType.WanderingTrader),
    (119, "讲台", "lectern", EntityType.Lectern),
    (120, "远古守卫者恶魂", "elder_guardian_ghost", EntityType.ElderGuardianGhost),
    (121, "狐狸", "fox", EntityType.Fox),
    (122, "蜜蜂", "bee", EntityType.Bee),
    (123, "猪灵", "piglin", EntityType.Piglin),
    (124, "疣猪兽", "hoglin", EntityType.Hoglin),
    (125, "炽足兽", "strider", EntityType.Strider),
    (126, "僵尸疣猪兽", "zoglin", EntityType.Zoglin),
    (127, "猪灵蛮兵", "piglin_brute", EntityType.PiglinBrute),
    (128, "山羊", "goat", EntityType.Goat),
    (129, "发光鱿鱼", "glow_squid", EntityType.GlowSquid),
    (130, "美西螈", "axolotl", EntityType.Axolotl),
    None,
    (132, "青蛙", "frog", None),
    (133, "蝌蚪", "tadpole", None),
    (134, "Allay", "allay", None),
    (218, "运输船", "chest_boat", None),
]


# 生物列表
# 数字ID，中文名，英文ID，网易版ID，是否是敌对生物
MOB_LIST = [
    (10, "鸡", "chicken", EntityType.Chicken, False),
    (11, "牛", "cow", EntityType.Cow, False),
    (12, "猪", "pig", EntityType.Pig, False),
    (13, "羊", "sheep", EntityType.Sheep, False),
    (14, "狼", "wolf", EntityType.Wolf, False),
    (15, "村民", "villager", EntityType.Villager, False),
    (16, "哞菇", "mooshroom", EntityType.MushroomCow, False),
    (17, "鱿鱼", "squid", EntityType.Squid, False),
    (18, "兔子", "rabbit", EntityType.Rabbit, False),
    (19, "蝙蝠", "bat", EntityType.Bat, False),
    (20, "铁傀儡", "iron_golem", EntityType.IronGolem, False),
    (21, "雪傀儡", "snow_golem", EntityType.SnowGolem, False),
    (22, "豹猫", "ocelot", EntityType.Ocelot, False),
    (23, "马", "horse", EntityType.Horse, False),
    (24, "驴", "donkey", EntityType.Donkey, False),
    (25, "骡", "mule", EntityType.Mule, False),
    (26, "骷髅马", "skeleton_horse", EntityType.SkeletonHorse, False),
    (27, "僵尸马", "zombie_horse", EntityType.ZombieHorse, False),
    (28, "北极熊", "polar_bear", EntityType.PolarBear, False),
    (29, "羊驼", "llama", EntityType.Llama, False),
    (30, "鹦鹉", "parrot", EntityType.Parrot, False),
    (31, "海豚", "dolphin", EntityType.Dolphin, False),
    (32, "僵尸", "zombie", EntityType.Zombie, True),
    (33, "苦力怕", "creeper", EntityType.Creeper, True),
    (34, "骷髅", "skeleton", EntityType.Skeleton, True),
    (35, "蜘蛛", "spider", EntityType.Spider, True),
    (36, "僵尸猪灵", "zombie_pigman", EntityType.PigZombie, True),
    (37, "史莱姆", "slime", EntityType.Slime, True),
    (38, "末影人", "enderman", EntityType.EnderMan, True),
    (39, "蠹虫", "silverfish", EntityType.Silverfish, True),
    (40, "洞穴蜘蛛", "cave_spider", EntityType.CaveSpider, True),
    (41, "恶魂", "ghast", EntityType.Ghast, True),
    (42, "岩浆怪", "magma_cube", EntityType.LavaSlime, True),
    (43, "烈焰人", "blaze", EntityType.Blaze, True),
    (44, "僵尸村民", "zombie_villager", EntityType.ZombieVillager, True),
    (45, "女巫", "witch", EntityType.Witch, True),
    (46, "流浪者", "stray", EntityType.Stray, True),
    (47, "尸壳", "husk", EntityType.Husk, True),
    (48, "凋灵骷髅", "wither_skeleton", EntityType.WitherSkeleton, True),
    (49, "守卫者", "guardian", EntityType.Guardian, True),
    (50, "远古守卫者", "elder_guardian", EntityType.ElderGuardian, True),
    (52, "凋灵", "wither", EntityType.WitherBoss, True),
    (53, "末影龙", "ender_dragon", EntityType.Dragon, True),
    (54, "潜影贝", "shulker", EntityType.Shulker, True),
    (55, "末影螨", "endermite", EntityType.Endermite, True),
    (57, "卫道士", "vindicator", EntityType.Vindicator, True),
    (58, "幻翼", "phantom", EntityType.Phantom, True),
    (59, "劫掠兽", "ravager", EntityType.IllagerBeast, True),
    (63, "玩家", "player", EntityType.Player, False),
    (74, "海龟", "turtle", EntityType.Turtle, False),
    (75, "猫", "cat", EntityType.Cat, False),
    (104, "唤魔者", "evocation_illager", EntityType.EvocationIllager, True),
    (105, "恼鬼", "vex", EntityType.Vex, True),
    (108, "河豚", "pufferfish", EntityType.Pufferfish, False),
    (109, "鲑鱼", "salmon", EntityType.Salmon, False),
    (110, "溺尸", "drowned", EntityType.Drowned, True),
    (111, "热带鱼", "tropicalfish", EntityType.Tropicalfish, False),
    (112, "鳕鱼", "cod", EntityType.Fish, False),
    (113, "熊猫", "panda", EntityType.Panda, False),
    (114, "掠夺者", "pillager", EntityType.Pillager, True),
    (115, "村民", "villager_v2", EntityType.VillagerV2, False),
    (116, "僵尸村民", "zombie_villager_v2", EntityType.ZombieVillagerV2, True),
    (118, "流浪商人", "wandering_trader", EntityType.WanderingTrader, False),
    (121, "狐狸", "fox", EntityType.Fox, False),
    (122, "蜜蜂", "bee", EntityType.Bee, False),
    (123, "猪灵", "piglin", EntityType.Piglin, True),
    (124, "疣猪兽", "hoglin", EntityType.Hoglin, True),
    (125, "炽足兽", "strider", EntityType.Strider, False),
    (126, "僵尸疣猪兽", "zoglin", EntityType.Zoglin, True),
    (127, "猪灵蛮兵", "piglin_brute", EntityType.PiglinBrute, True),
    (128, "山羊", "goat", EntityType.Goat, False),
    (129, "发光鱿鱼", "glow_squid", EntityType.GlowSquid, False),
    (130, "美西螈", "axolotl", EntityType.Axolotl, False),
    (132, "青蛙", "frog", None, False),
    (133, "蝌蚪", "tadpole", None, False),
    (134, "Allay", "allay", None, False),
]


# 友好生物列表
# 数字ID，中文名，英文ID，网易版ID
FRIENDLY_MOB_LIST = [
    (10, "鸡", "chicken", EntityType.Chicken),
    (11, "牛", "cow", EntityType.Cow),
    (12, "猪", "pig", EntityType.Pig),
    (13, "羊", "sheep", EntityType.Sheep),
    (14, "狼", "wolf", EntityType.Wolf),
    (15, "村民", "villager", EntityType.Villager),
    (16, "哞菇", "mooshroom", EntityType.MushroomCow),
    (17, "鱿鱼", "squid", EntityType.Squid),
    (18, "兔子", "rabbit", EntityType.Rabbit),
    (19, "蝙蝠", "bat", EntityType.Bat),
    (20, "铁傀儡", "iron_golem", EntityType.IronGolem),
    (21, "雪傀儡", "snow_golem", EntityType.SnowGolem),
    (22, "豹猫", "ocelot", EntityType.Ocelot),
    (23, "马", "horse", EntityType.Horse),
    (24, "驴", "donkey", EntityType.Donkey),
    (25, "骡", "mule", EntityType.Mule),
    (26, "骷髅马", "skeleton_horse", EntityType.SkeletonHorse),
    (27, "僵尸马", "zombie_horse", EntityType.ZombieHorse),
    (28, "北极熊", "polar_bear", EntityType.PolarBear),
    (29, "羊驼", "llama", EntityType.Llama),
    (30, "鹦鹉", "parrot", EntityType.Parrot),
    (31, "海豚", "dolphin", EntityType.Dolphin),
    (74, "海龟", "turtle", EntityType.Turtle),
    (75, "猫", "cat", EntityType.Cat),
    (108, "河豚", "pufferfish", EntityType.Pufferfish),
    (109, "鲑鱼", "salmon", EntityType.Salmon),
    (111, "热带鱼", "tropicalfish", EntityType.Tropicalfish),
    (112, "鳕鱼", "cod", EntityType.Fish),
    (113, "熊猫", "panda", EntityType.Panda),
    (115, "村民", "villager_v2", EntityType.VillagerV2),
    (118, "流浪商人", "wandering_trader", EntityType.WanderingTrader),
    (121, "狐狸", "fox", EntityType.Fox),
    (122, "蜜蜂", "bee", EntityType.Bee),
    (125, "炽足兽", "strider", EntityType.Strider),
    (128, "山羊", "goat", 4992),
    (129, "发光鱿鱼", "glow_squid", EntityType.GlowSquid),
    (130, "美西螈", "axolotl", EntityType.Axolotl),
    (132, "青蛙", "frog", None),
    (133, "蝌蚪", "tadpole", None),
    (134, "Allay", "allay", None),
]


# 敌对生物列表
# 数字ID，中文名，英文ID，网易版ID
HOSTILE_MOB_LIST = [
    (32, "僵尸", "zombie", EntityType.Zombie),
    (33, "苦力怕", "creeper", EntityType.Creeper),
    (34, "骷髅", "skeleton", EntityType.Skeleton),
    (35, "蜘蛛", "spider", EntityType.Spider),
    (36, "僵尸猪灵", "zombie_pigman", EntityType.PigZombie),
    (37, "史莱姆", "slime", EntityType.Slime),
    (38, "末影人", "enderman", EntityType.EnderMan),
    (39, "蠹虫", "silverfish", EntityType.Silverfish),
    (40, "洞穴蜘蛛", "cave_spider", EntityType.CaveSpider),
    (41, "恶魂", "ghast", EntityType.Ghast),
    (42, "岩浆怪", "magma_cube", EntityType.LavaSlime),
    (43, "烈焰人", "blaze", EntityType.Blaze),
    (44, "僵尸村民", "zombie_villager", EntityType.ZombieVillager),
    (45, "女巫", "witch", EntityType.Witch),
    (46, "流浪者", "stray", EntityType.Stray),
    (47, "尸壳", "husk", EntityType.Husk),
    (48, "凋灵骷髅", "wither_skeleton", EntityType.WitherSkeleton),
    (49, "守卫者", "guardian", EntityType.Guardian),
    (50, "远古守卫者", "elder_guardian", EntityType.ElderGuardian),
    (54, "潜影贝", "shulker", EntityType.Shulker),
    (55, "末影螨", "endermite", EntityType.Endermite),
    (57, "卫道士", "vindicator", EntityType.Vindicator),
    (58, "幻翼", "phantom", EntityType.Phantom),
    (59, "劫掠兽", "ravager", EntityType.IllagerBeast),
    (104, "唤魔者", "evocation_illager", EntityType.EvocationIllager),
    (105, "恼鬼", "vex", EntityType.Vex),
    (110, "溺尸", "drowned", EntityType.Drowned),
    (114, "掠夺者", "pillager", EntityType.Pillager),
    (116, "僵尸村民", "zombie_villager_v2", EntityType.ZombieVillagerV2),
    (123, "猪灵", "piglin", EntityType.Piglin),
    (124, "疣猪兽", "hoglin", EntityType.Hoglin),
    (126, "僵尸疣猪兽", "zoglin", EntityType.Zoglin),
    (127, "猪灵蛮兵", "piglin_brute", EntityType.PiglinBrute),
]


# 具有攻击力的生物列表
# 数字ID，中文名，英文ID，网易版ID
ATTACKABLE_MOB_LIST = [
    (14, "狼", "wolf", EntityType.Wolf),
    (20, "铁傀儡", "iron_golem", EntityType.IronGolem),
    (21, "雪傀儡", "snow_golem", EntityType.SnowGolem),
    (22, "豹猫", "ocelot", EntityType.Ocelot),
    (28, "北极熊", "polar_bear", EntityType.PolarBear),
    (31, "海豚", "dolphin", EntityType.Dolphin),
    (32, "僵尸", "zombie", EntityType.Zombie),
    (33, "苦力怕", "creeper", EntityType.Creeper),
    (34, "骷髅", "skeleton", EntityType.Skeleton),
    (35, "蜘蛛", "spider", EntityType.Spider),
    (36, "僵尸猪灵", "zombie_pigman", EntityType.PigZombie),
    (37, "史莱姆", "slime", EntityType.Slime),
    (38, "末影人", "enderman", EntityType.EnderMan),
    (39, "蠹虫", "silverfish", EntityType.Silverfish),
    (40, "洞穴蜘蛛", "cave_spider", EntityType.CaveSpider),
    (41, "恶魂", "ghast", EntityType.Ghast),
    (42, "岩浆怪", "magma_cube", EntityType.LavaSlime),
    (43, "烈焰人", "blaze", EntityType.Blaze),
    (44, "僵尸村民", "zombie_villager", EntityType.ZombieVillager),
    (45, "女巫", "witch", EntityType.Witch),
    (46, "流浪者", "stray", EntityType.Stray),
    (47, "尸壳", "husk", EntityType.Husk),
    (48, "凋灵骷髅", "wither_skeleton", EntityType.WitherSkeleton),
    (49, "守卫者", "guardian", EntityType.Guardian),
    (50, "远古守卫者", "elder_guardian", EntityType.ElderGuardian),
    (54, "潜影贝", "shulker", EntityType.Shulker),
    (55, "末影螨", "endermite", EntityType.Endermite),
    (57, "卫道士", "vindicator", EntityType.Vindicator),
    (58, "幻翼", "phantom", EntityType.Phantom),
    (59, "劫掠兽", "ravager", EntityType.IllagerBeast),
    (75, "猫", "cat", EntityType.Cat),
    (104, "唤魔者", "evocation_illager", EntityType.EvocationIllager),
    (105, "恼鬼", "vex", EntityType.Vex),
    (108, "河豚", "pufferfish", EntityType.Pufferfish),
    (110, "溺尸", "drowned", EntityType.Drowned),
    (113, "熊猫", "panda", EntityType.Panda),
    (114, "掠夺者", "pillager", EntityType.Pillager),
    (116, "僵尸村民", "zombie_villager_v2", EntityType.ZombieVillagerV2),
    (122, "蜜蜂", "bee", EntityType.Bee),
    (123, "猪灵", "piglin", EntityType.Piglin),
    (124, "疣猪兽", "hoglin", EntityType.Hoglin),
    (125, "炽足兽", "strider", EntityType.Strider),
    (126, "僵尸疣猪兽", "zoglin", EntityType.Zoglin),
    (127, "猪灵蛮兵", "piglin_brute", EntityType.PiglinBrute),
    (128, "山羊", "goat", EntityType.Goat),
]


# 用于将实体网易版ID转换为数字ID的字典
ENTITY_ID_DICT = {
    EntityType.Chicken: 10,
    EntityType.Cow: 11,
    EntityType.Pig: 12,
    EntityType.Sheep: 13,
    EntityType.Wolf: 14,
    EntityType.Villager: 15,
    EntityType.MushroomCow: 16,
    EntityType.Squid: 17,
    EntityType.Rabbit: 18,
    EntityType.Bat: 19,
    EntityType.IronGolem: 20,
    EntityType.SnowGolem: 21,
    EntityType.Ocelot: 22,
    EntityType.Horse: 23,
    EntityType.Donkey: 24,
    EntityType.Mule: 25,
    EntityType.SkeletonHorse: 26,
    EntityType.ZombieHorse: 27,
    EntityType.PolarBear: 28,
    EntityType.Llama: 29,
    EntityType.Parrot: 30,
    EntityType.Dolphin: 31,
    EntityType.Zombie: 32,
    EntityType.Creeper: 33,
    EntityType.Skeleton: 34,
    EntityType.Spider: 35,
    EntityType.PigZombie: 36,
    EntityType.Slime: 37,
    EntityType.EnderMan: 38,
    EntityType.Silverfish: 39,
    EntityType.CaveSpider: 40,
    EntityType.Ghast: 41,
    EntityType.LavaSlime: 42,
    EntityType.Blaze: 43,
    EntityType.ZombieVillager: 44,
    EntityType.Witch: 45,
    EntityType.Stray: 46,
    EntityType.Husk: 47,
    EntityType.WitherSkeleton: 48,
    EntityType.Guardian: 49,
    EntityType.ElderGuardian: 50,
    EntityType.Npc: 51,
    EntityType.WitherBoss: 52,
    EntityType.Dragon: 53,
    EntityType.Shulker: 54,
    EntityType.Endermite: 55,
    EntityType.Agent: 56,
    EntityType.Vindicator: 57,
    EntityType.Phantom: 58,
    EntityType.IllagerBeast: 59,
    EntityType.ArmorStand: 61,
    EntityType.TripodCamera: 62,
    EntityType.Player: 63,
    EntityType.ItemEntity: 64,
    EntityType.PrimedTnt: 65,
    EntityType.FallingBlock: 66,
    EntityType.MovingBlock: 67,
    EntityType.ExperiencePotion: 68,
    EntityType.Experience: 69,
    EntityType.EyeOfEnder: 70,
    EntityType.EnderCrystal: 71,
    EntityType.FireworksRocket: 72,
    EntityType.Trident: 73,
    EntityType.Turtle: 74,
    EntityType.Cat: 75,
    EntityType.ShulkerBullet: 76,
    EntityType.FishingHook: 77,
    EntityType.Chalkboard: 78,
    EntityType.DragonFireball: 79,
    EntityType.Arrow: 80,
    EntityType.Snowball: 81,
    EntityType.ThrownEgg: 82,
    EntityType.Painting: 83,
    EntityType.Minecart: 84,
    EntityType.LargeFireball: 85,
    EntityType.ThrownPotion: 86,
    EntityType.Enderpearl: 87,
    EntityType.LeashKnot: 88,
    EntityType.WitherSkull: 89,
    EntityType.BoatRideable: 90,
    EntityType.WitherSkullDangerous: 91,
    EntityType.LightningBolt: 93,
    EntityType.SmallFireball: 94,
    EntityType.AreaEffectCloud: 95,
    EntityType.MinecartHopper: 96,
    EntityType.MinecartTNT: 97,
    EntityType.MinecartChest: 98,
    EntityType.MinecartCommandBlock: 100,
    EntityType.LingeringPotion: 101,
    EntityType.LlamaSpit: 102,
    EntityType.EvocationFang: 103,
    EntityType.EvocationIllager: 104,
    EntityType.Vex: 105,
    EntityType.IceBomb: 106,
    EntityType.Balloon: 107,
    EntityType.Pufferfish: 108,
    EntityType.Salmon: 109,
    EntityType.Drowned: 110,
    EntityType.Tropicalfish: 111,
    EntityType.Fish: 112,
    EntityType.Panda: 113,
    EntityType.Pillager: 114,
    EntityType.VillagerV2: 115,
    EntityType.ZombieVillagerV2: 116,
    EntityType.Shield: 117,
    EntityType.WanderingTrader: 118,
    EntityType.Lectern: 119,
    EntityType.ElderGuardianGhost: 120,
    EntityType.Fox: 121,
    EntityType.Bee: 122,
    EntityType.Piglin: 123,
    EntityType.Hoglin: 124,
    EntityType.Strider: 125,
    EntityType.Zoglin: 126,
    EntityType.PiglinBrute: 127,
    EntityType.Goat: 128,
    EntityType.GlowSquid: 129,
    EntityType.Axolotl: 130,
}


# 用于将药水效果英文ID转换为中文名的字典
EFFECT_DICT = {
    'speed': "速度",
    'slowness': "缓慢",
    'haste': "急速",
    'mining_fatigue': "开采疲劳",
    'strength': "力量",
    'instant_health': "瞬间治疗",
    'instant_damage': "瞬间伤害",
    'jump_boost': "跳跃增强",
    'nausea': "反胃",
    'regeneration': "生命恢复",
    'resistance': "抗性",
    'fire_resistance': "抗火",
    'water_breathing': "水下呼吸",
    'invisibility': "隐身",
    'blindness': "失明",
    'night_vision': "夜视",
    'hunger': "饥饿",
    'weakness': "虚弱",
    'poison': "中毒",
    'wither': "凋灵",
    'health_boost': "生命提升",
    'absorption': "伤害吸收",
    'saturation': "饱和",
    'levitation': "漂浮",
    'fatal_poison': "中毒",
    'conduit_power': "潮涌能量",
    'slow_falling': "缓降",
    'bad_omen': "凶兆",
    'village_hero': "村庄英雄",
    'darkness': "黑暗",
    'trial_omen': "试炼之兆",
    'weaving': "盘丝",
    'wind_charged': "蓄风",
    'infested': "寄生",
    'oozing': "渗浆",
}


# 用于将生物群系英文ID转换为中文名的字典
BIOME_DICT = {
    'ocean': "海洋",
    'plains': "平原",
    'desert': "沙漠",
    'extreme_hills': "山地",
    'forest': "森林",
    'taiga': "针叶林",
    'swampland': "沼泽",
    'river': "河流",
    'hell': "下界荒地",
    'the_end': "末路之地",
    'legacy_frozen_ocean': "冻洋",
    'frozen_river': "冻河",
    'ice_plains': "积雪的冻原",
    'ice_mountains': "雪山",
    'mushroom_island': "蘑菇岛",
    'mushroom_island_shore': "蘑菇岛岸",
    'beach': "沙滩",
    'desert_hills': "沙漠丘陵",
    'forest_hills': "繁茂的丘陵",
    'taiga_hills': "针叶林丘陵",
    'extreme_hills_edge': "山地边缘",
    'jungle': "丛林",
    'jungle_hills': "丛林丘陵",
    'jungle_edge': "丛林边缘",
    'deep_ocean': "深海",
    'stone_beach': "石岸",
    'cold_beach': "积雪的沙滩",
    'birch_forest': "桦木森林",
    'birch_forest_hills': "桦木森林丘陵",
    'roofed_forest': "黑森林",
    'cold_taiga': "积雪的针叶林",
    'cold_taiga_hills': "积雪的针叶林丘陵",
    'mega_taiga': "巨型针叶林",
    'mega_taiga_hills': "巨型针叶林丘陵",
    'extreme_hills_plus_trees': "繁茂的山地",
    'savanna': "热带草原",
    'savanna_plateau': "热带高原",
    'mesa': "恶地",
    'mesa_plateau_stone': "繁茂的恶地高原",
    'mesa_plateau': "恶地高原",
    'warm_ocean': "暖水海洋",
    'deep_warm_ocean': "暖水深海",
    'lukewarm_ocean': "温水海洋",
    'deep_lukewarm_ocean': "温水深海",
    'cold_ocean': "冷水海洋",
    'deep_cold_ocean': "冷水深海",
    'frozen_ocean': "封冻海洋",
    'deep_frozen_ocean': "封冻深海",
    'bamboo_jungle': "竹林",
    'bamboo_jungle_hills': "竹林丘陵",
    'sunflower_plains': "向日葵平原",
    'desert_mutated': "沙漠湖泊",
    'extreme_hills_mutated': "沙砾山地",
    'flower_forest': "繁花森林",
    'taiga_mutated': "针叶林山地",
    'swampland_mutated': "沼泽丘陵",
    'ice_plains_spikes': "冰刺平原",
    'jungle_mutated': "丛林变种",
    'jungle_edge_mutated': "丛林边缘变种",
    'birch_forest_mutated': "高大桦木森林",
    'birch_forest_hills_mutated': "高大桦木丘陵",
    'roofed_forest_mutated': "黑森林丘陵",
    'cold_taiga_mutated': "积雪的针叶林山地",
    'redwood_taiga_mutated': "巨型云杉针叶林",
    'redwood_taiga_hills_mutated': "巨型云杉针叶林丘陵",
    'extreme_hills_plus_trees_mutated': "沙砾山地+",
    'savanna_mutated': "破碎的热带草原",
    'savanna_plateau_mutated': "破碎的热带高原",
    'mesa_bryce': "被风蚀的恶地",
    'mesa_plateau_stone_mutated': "繁茂的恶地高原变种",
    'mesa_plateau_mutated': "恶地高原变种",
}


# 用于将结构数字ID转换为中文名或英文ID的字典
STRUCTURE_DICT = {
    1: ("末地城", "endcity"),
    2: ("下界要塞", "fortress"),
    3: ("废弃矿井", "mineshaft"),
    4: ("海底神殿", "monument"),
    5: ("地牢", "stronghold"),
    6: ("沙漠神殿/雪屋/丛林/神庙/女巫小屋", "temple"),
    7: ("村庄", "village"),
    8: ("林地府邸", "mansion"),
    9: ("沉船", "shipwreck"),
    10: ("埋藏的宝藏", "buriedtreasure"),
    11: ("水下遗迹", "ruins"),
    12: ("掠夺者前哨站", "pillageroutpost"),
    13: ("废弃传送门", "ruinedportal"),
    14: ("堡垒遗迹", "bastionremnant"),
}


# 方块列表
BLOCK_LIST = [
    "acacia_button",
    "acacia_door",
    "acacia_fence_gate",
    "acacia_pressure_plate",
    "acacia_stairs",
    "acacia_standing_sign",
    "acacia_trapdoor",
    "acacia_wall_sign",
    "activator_rail",
    "air",
    "allow",
    "amethyst_block",
    "amethyst_cluster",
    "ancient_debris",
    "andesite_stairs",
    "anvil",
    "azalea",
    "azalea_leaves",
    "azalea_leaves_flowered",
    "bamboo",
    "bamboo_sapling",
    "barrel",
    "barrier",
    "basalt",
    "beacon",
    "bed",
    "bedrock",
    "bee_nest",
    "beehive",
    "beetroot",
    "bell",
    "big_dripleaf",
    "birch_button",
    "birch_door",
    "birch_fence_gate",
    "birch_pressure_plate",
    "birch_stairs",
    "birch_standing_sign",
    "birch_trapdoor",
    "birch_wall_sign",
    "black_candle",
    "black_candle_cake",
    "black_glazed_terracotta",
    "blackstone",
    "blackstone_double_slab",
    "blackstone_slab",
    "blackstone_stairs",
    "blackstone_wall",
    "blast_furnace",
    "blue_candle",
    "blue_candle_cake",
    "blue_glazed_terracotta",
    "blue_ice",
    "bone_block",
    "bookshelf",
    "border_block",
    "brewing_stand",
    "brick_block",
    "brick_stairs",
    "brown_candle",
    "brown_candle_cake",
    "brown_glazed_terracotta",
    "brown_mushroom",
    "brown_mushroom_block",
    "bubble_column",
    "budding_amethyst",
    "cactus",
    "cake",
    "calcite",
    "camera",
    "campfire",
    "candle",
    "candle_cake",
    "carpet",
    "carrots",
    "cartography_table",
    "carved_pumpkin",
    "cauldron",
    "cave_vines",
    "cave_vines_body_with_berries",
    "cave_vines_head_with_berries",
    "chain",
    "chain_command_block",
    "chemical_heat",
    "chemistry_table",
    "chest",
    "chiseled_deepslate",
    "chiseled_nether_bricks",
    "chiseled_polished_blackstone",
    "chorus_flower",
    "chorus_plant",
    "clay",
    "client_request_placeholder_block",
    "coal_block",
    "coal_ore",
    "cobbled_deepslate",
    "cobbled_deepslate_double_slab",
    "cobbled_deepslate_slab",
    "cobbled_deepslate_stairs",
    "cobbled_deepslate_wall",
    "cobblestone",
    "cobblestone_wall",
    "cocoa",
    "colored_torch_bp",
    "colored_torch_rg",
    "command_block",
    "composter",
    "concrete",
    "concretePowder",
    "conduit",
    "copper_block",
    "copper_ore",
    "coral",
    "coral_block",
    "coral_fan",
    "coral_fan_dead",
    "coral_fan_hang",
    "coral_fan_hang2",
    "coral_fan_hang3",
    "cracked_deepslate_bricks",
    "cracked_deepslate_tiles",
    "cracked_nether_bricks",
    "cracked_polished_blackstone_bricks",
    "crafting_table",
    "crimson_button",
    "crimson_door",
    "crimson_double_slab",
    "crimson_fence",
    "crimson_fence_gate",
    "crimson_fungus",
    "crimson_hyphae",
    "crimson_nylium",
    "crimson_planks",
    "crimson_pressure_plate",
    "crimson_roots",
    "crimson_slab",
    "crimson_stairs",
    "crimson_standing_sign",
    "crimson_stem",
    "crimson_trapdoor",
    "crimson_wall_sign",
    "crying_obsidian",
    "cut_copper",
    "cut_copper_slab",
    "cut_copper_stairs",
    "cyan_candle",
    "cyan_candle_cake",
    "cyan_glazed_terracotta",
    "dark_oak_button",
    "dark_oak_door",
    "dark_oak_fence_gate",
    "dark_oak_pressure_plate",
    "dark_oak_stairs",
    "dark_oak_trapdoor",
    "dark_prismarine_stairs",
    "darkoak_standing_sign",
    "darkoak_wall_sign",
    "daylight_detector",
    "daylight_detector_inverted",
    "deadbush",
    "deepslate",
    "deepslate_brick_double_slab",
    "deepslate_brick_slab",
    "deepslate_brick_stairs",
    "deepslate_brick_wall",
    "deepslate_bricks",
    "deepslate_coal_ore",
    "deepslate_copper_ore",
    "deepslate_diamond_ore",
    "deepslate_emerald_ore",
    "deepslate_gold_ore",
    "deepslate_iron_ore",
    "deepslate_lapis_ore",
    "deepslate_redstone_ore",
    "deepslate_tile_double_slab",
    "deepslate_tile_slab",
    "deepslate_tile_stairs",
    "deepslate_tile_wall",
    "deepslate_tiles",
    "deny",
    "detector_rail",
    "diamond_block",
    "diamond_ore",
    "diorite_stairs",
    "dirt",
    "dirt_with_roots",
    "dispenser",
    "double_cut_copper_slab",
    "double_plant",
    "double_stone_slab",
    "double_stone_slab2",
    "double_stone_slab3",
    "double_stone_slab4",
    "double_wooden_slab",
    "dragon_egg",
    "dried_kelp_block",
    "dripstone_block",
    "dropper",
    "element_0",
    "element_1",
    "element_10",
    "element_100",
    "element_101",
    "element_102",
    "element_103",
    "element_104",
    "element_105",
    "element_106",
    "element_107",
    "element_108",
    "element_109",
    "element_11",
    "element_110",
    "element_111",
    "element_112",
    "element_113",
    "element_114",
    "element_115",
    "element_116",
    "element_117",
    "element_118",
    "element_12",
    "element_13",
    "element_14",
    "element_15",
    "element_16",
    "element_17",
    "element_18",
    "element_19",
    "element_2",
    "element_20",
    "element_21",
    "element_22",
    "element_23",
    "element_24",
    "element_25",
    "element_26",
    "element_27",
    "element_28",
    "element_29",
    "element_3",
    "element_30",
    "element_31",
    "element_32",
    "element_33",
    "element_34",
    "element_35",
    "element_36",
    "element_37",
    "element_38",
    "element_39",
    "element_4",
    "element_40",
    "element_41",
    "element_42",
    "element_43",
    "element_44",
    "element_45",
    "element_46",
    "element_47",
    "element_48",
    "element_49",
    "element_5",
    "element_50",
    "element_51",
    "element_52",
    "element_53",
    "element_54",
    "element_55",
    "element_56",
    "element_57",
    "element_58",
    "element_59",
    "element_6",
    "element_60",
    "element_61",
    "element_62",
    "element_63",
    "element_64",
    "element_65",
    "element_66",
    "element_67",
    "element_68",
    "element_69",
    "element_7",
    "element_70",
    "element_71",
    "element_72",
    "element_73",
    "element_74",
    "element_75",
    "element_76",
    "element_77",
    "element_78",
    "element_79",
    "element_8",
    "element_80",
    "element_81",
    "element_82",
    "element_83",
    "element_84",
    "element_85",
    "element_86",
    "element_87",
    "element_88",
    "element_89",
    "element_9",
    "element_90",
    "element_91",
    "element_92",
    "element_93",
    "element_94",
    "element_95",
    "element_96",
    "element_97",
    "element_98",
    "element_99",
    "emerald_block",
    "emerald_ore",
    "enchanting_table",
    "end_brick_stairs",
    "end_bricks",
    "end_gateway",
    "end_portal",
    "end_portal_frame",
    "end_rod",
    "end_stone",
    "ender_chest",
    "exposed_copper",
    "exposed_cut_copper",
    "exposed_cut_copper_slab",
    "exposed_cut_copper_stairs",
    "exposed_double_cut_copper_slab",
    "farmland",
    "fence",
    "fence_gate",
    "fire",
    "fletching_table",
    "flower_pot",
    "flowering_azalea",
    "flowing_lava",
    "flowing_water",
    "frame",
    "frosted_ice",
    "furnace",
    "gilded_blackstone",
    "glass",
    "glass_pane",
    "glow_frame",
    "glow_lichen",
    "glowingobsidian",
    "glowstone",
    "gold_block",
    "gold_ore",
    "golden_rail",
    "granite_stairs",
    "grass",
    "grass_path",
    "gravel",
    "gray_candle",
    "gray_candle_cake",
    "gray_glazed_terracotta",
    "green_candle",
    "green_candle_cake",
    "green_glazed_terracotta",
    "grindstone",
    "hanging_roots",
    "hard_glass",
    "hard_glass_pane",
    "hard_stained_glass",
    "hard_stained_glass_pane",
    "hardened_clay",
    "hay_block",
    "heavy_weighted_pressure_plate",
    "honey_block",
    "honeycomb_block",
    "hopper",
    "ice",
    "infested_deepslate",
    "info_update",
    "info_update2",
    "invisibleBedrock",
    "iron_bars",
    "iron_block",
    "iron_door",
    "iron_ore",
    "iron_trapdoor",
    "jigsaw",
    "jukebox",
    "jungle_button",
    "jungle_door",
    "jungle_fence_gate",
    "jungle_pressure_plate",
    "jungle_stairs",
    "jungle_standing_sign",
    "jungle_trapdoor",
    "jungle_wall_sign",
    "kelp",
    "ladder",
    "lantern",
    "lapis_block",
    "lapis_ore",
    "large_amethyst_bud",
    "lava",
    "lava_cauldron",
    "leaves",
    "leaves2",
    "lectern",
    "lever",
    "light_block",
    "light_blue_candle",
    "light_blue_candle_cake",
    "light_blue_glazed_terracotta",
    "light_gray_candle",
    "light_gray_candle_cake",
    "light_weighted_pressure_plate",
    "lightning_rod",
    "lime_candle",
    "lime_candle_cake",
    "lime_glazed_terracotta",
    "lit_blast_furnace",
    "lit_deepslate_redstone_ore",
    "lit_furnace",
    "lit_pumpkin",
    "lit_redstone_lamp",
    "lit_redstone_ore",
    "lit_smoker",
    "lodestone",
    "log",
    "log2",
    "loom",
    "magenta_candle",
    "magenta_candle_cake",
    "magenta_glazed_terracotta",
    "magma",
    "medium_amethyst_bud",
    "melon_block",
    "melon_stem",
    "mob_spawner",
    "monster_egg",
    "moss_block",
    "moss_carpet",
    "mossy_cobblestone",
    "mossy_cobblestone_stairs",
    "mossy_stone_brick_stairs",
    "movingBlock",
    "mycelium",
    "mysterious_frame",
    "mysterious_frame_slot",
    "nether_brick",
    "nether_brick_fence",
    "nether_brick_stairs",
    "nether_gold_ore",
    "nether_sprouts",
    "nether_wart",
    "nether_wart_block",
    "netherite_block",
    "netherrack",
    "netherreactor",
    "normal_stone_stairs",
    "noteblock",
    "oak_stairs",
    "observer",
    "obsidian",
    "orange_candle",
    "orange_candle_cake",
    "orange_glazed_terracotta",
    "oxidized_copper",
    "oxidized_cut_copper",
    "oxidized_cut_copper_slab",
    "oxidized_cut_copper_stairs",
    "oxidized_double_cut_copper_slab",
    "packed_ice",
    "pink_candle",
    "pink_candle_cake",
    "pink_glazed_terracotta",
    "piston",
    "pistonArmCollision",
    "planks",
    "podzol",
    "pointed_dripstone",
    "polished_andesite_stairs",
    "polished_basalt",
    "polished_blackstone",
    "polished_blackstone_brick_double_slab",
    "polished_blackstone_brick_slab",
    "polished_blackstone_brick_stairs",
    "polished_blackstone_brick_wall",
    "polished_blackstone_bricks",
    "polished_blackstone_button",
    "polished_blackstone_double_slab",
    "polished_blackstone_pressure_plate",
    "polished_blackstone_slab",
    "polished_blackstone_stairs",
    "polished_blackstone_wall",
    "polished_deepslate",
    "polished_deepslate_double_slab",
    "polished_deepslate_slab",
    "polished_deepslate_stairs",
    "polished_deepslate_wall",
    "polished_diorite_stairs",
    "polished_granite_stairs",
    "portal",
    "potatoes",
    "powder_snow",
    "powered_comparator",
    "powered_repeater",
    "prismarine",
    "prismarine_bricks_stairs",
    "prismarine_stairs",
    "pumpkin",
    "pumpkin_stem",
    "purple_candle",
    "purple_candle_cake",
    "purple_glazed_terracotta",
    "purpur_block",
    "purpur_stairs",
    "quartz_block",
    "quartz_bricks",
    "quartz_ore",
    "quartz_stairs",
    "rail",
    "raw_copper_block",
    "raw_gold_block",
    "raw_iron_block",
    "red_candle",
    "red_candle_cake",
    "red_flower",
    "red_glazed_terracotta",
    "red_mushroom",
    "red_mushroom_block",
    "red_nether_brick",
    "red_nether_brick_stairs",
    "red_sandstone",
    "red_sandstone_stairs",
    "redstone_block",
    "redstone_lamp",
    "redstone_ore",
    "redstone_torch",
    "redstone_wire",
    "reeds",
    "repeating_command_block",
    "reserved6",
    "respawn_anchor",
    "sand",
    "sandstone",
    "sandstone_stairs",
    "sapling",
    "scaffolding",
    "sculk",
    "sculk_catalyst",
    "sculk_sensor",
    "sculk_shrieker",
    "sculk_vein",
    "sea_pickle",
    "seagrass",
    "seaLantern",
    "shroomlight",
    "shulker_box",
    "silver_glazed_terracotta",
    "skull",
    "slime",
    "small_amethyst_bud",
    "small_dripleaf_block",
    "smithing_table",
    "smoker",
    "smooth_basalt",
    "smooth_quartz_stairs",
    "smooth_red_sandstone_stairs",
    "smooth_sandstone_stairs",
    "smooth_stone",
    "snow",
    "snow_layer",
    "soul_campfire",
    "soul_fire",
    "soul_lantern",
    "soul_sand",
    "soul_soil",
    "soul_torch",
    "sponge",
    "spore_blossom",
    "spruce_button",
    "spruce_door",
    "spruce_fence_gate",
    "spruce_pressure_plate",
    "spruce_stairs",
    "spruce_standing_sign",
    "spruce_trapdoor",
    "spruce_wall_sign",
    "stained_glass",
    "stained_glass_pane",
    "stained_hardened_clay",
    "standing_banner",
    "standing_sign",
    "sticky_piston",
    "stickyPistonArmCollision",
    "stone",
    "stone_brick_stairs",
    "stone_button",
    "stone_pressure_plate",
    "stone_slab",
    "stone_slab2",
    "stone_slab3",
    "stone_slab4",
    "stone_stairs",
    "stonebrick",
    "stonecutter",
    "stonecutter_block",
    "stripped_acacia_log",
    "stripped_birch_log",
    "stripped_crimson_hyphae",
    "stripped_crimson_stem",
    "stripped_dark_oak_log",
    "stripped_jungle_log",
    "stripped_oak_log",
    "stripped_spruce_log",
    "stripped_warped_hyphae",
    "stripped_warped_stem",
    "structure_block",
    "structure_void",
    "sweet_berry_bush",
    "tallgrass",
    "target",
    "tinted_glass",
    "tnt",
    "torch",
    "trapdoor",
    "trapped_chest",
    "tripWire",
    "tripwire_hook",
    "tuff",
    "turtle_egg",
    "twisting_vines",
    "underwater_torch",
    "undyed_shulker_box",
    "unknown",
    "unlit_redstone_torch",
    "unpowered_comparator",
    "unpowered_repeater",
    "vine",
    "wall_banner",
    "wall_sign",
    "warped_button",
    "warped_door",
    "warped_double_slab",
    "warped_fence",
    "warped_fence_gate",
    "warped_fungus",
    "warped_hyphae",
    "warped_nylium",
    "warped_planks",
    "warped_pressure_plate",
    "warped_roots",
    "warped_slab",
    "warped_stairs",
    "warped_standing_sign",
    "warped_stem",
    "warped_trapdoor",
    "warped_wall_sign",
    "warped_wart_block",
    "water",
    "waterlily",
    "waxed_copper",
    "waxed_cut_copper",
    "waxed_cut_copper_slab",
    "waxed_cut_copper_stairs",
    "waxed_double_cut_copper_slab",
    "waxed_exposed_copper",
    "waxed_exposed_cut_copper",
    "waxed_exposed_cut_copper_slab",
    "waxed_exposed_cut_copper_stairs",
    "waxed_exposed_double_cut_copper_slab",
    "waxed_oxidized_copper",
    "waxed_oxidized_cut_copper",
    "waxed_oxidized_cut_copper_slab",
    "waxed_oxidized_cut_copper_stairs",
    "waxed_oxidized_double_cut_copper_slab",
    "waxed_weathered_copper",
    "waxed_weathered_cut_copper",
    "waxed_weathered_cut_copper_slab",
    "waxed_weathered_cut_copper_stairs",
    "waxed_weathered_double_cut_copper_slab",
    "weathered_copper",
    "weathered_cut_copper",
    "weathered_cut_copper_slab",
    "weathered_cut_copper_stairs",
    "weathered_double_cut_copper_slab",
    "web",
    "weeping_vines",
    "wheat",
    "white_candle",
    "white_candle_cake",
    "white_glazed_terracotta",
    "wither_rose",
    "wood",
    "wooden_button",
    "wooden_door",
    "wooden_pressure_plate",
    "wooden_slab",
    "wool",
    "yellow_candle",
    "yellow_candle_cakez",
    "yellow_flower",
    "yellow_glazed_terracotta",
]


# 物品列表
ITEM_LIST = [
    "acacia_boat",
    "acacia_button",
    "acacia_door",
    "acacia_fence_gate",
    "acacia_pressure_plate",
    "acacia_sign",
    "acacia_stairs",
    "acacia_standing_sign",
    "acacia_trapdoor",
    "acacia_wall_sign",
    "activator_rail",
    "agent_spawn_egg",
    "air",
    "allow",
    "amethyst_block",
    "amethyst_cluster",
    "amethyst_shard",
    "ancient_debris",
    "andesite_stairs",
    "anvil",
    "apple",
    "armor_stand",
    "arrow",
    "axolotl_bucket",
    "axolotl_spawn_egg",
    "azalea",
    "azalea_leaves",
    "azalea_leaves_flowered",
    "baked_potato",
    "balloon",
    "bamboo",
    "bamboo_sapling",
    "banner",
    "banner_pattern",
    "barrel",
    "barrier",
    "basalt",
    "bat_spawn_egg",
    "beacon",
    "bed",
    "bedrock",
    "bee_nest",
    "bee_spawn_egg",
    "beef",
    "beehive",
    "beetroot",
    "beetroot_seeds",
    "beetroot_soup",
    "bell",
    "big_dripleaf",
    "birch_boat",
    "birch_button",
    "birch_door",
    "birch_fence_gate",
    "birch_pressure_plate",
    "birch_sign",
    "birch_stairs",
    "birch_standing_sign",
    "birch_trapdoor",
    "birch_wall_sign",
    "black_candle",
    "black_candle_cake",
    "black_dye",
    "black_glazed_terracotta",
    "blackstone",
    "blackstone_double_slab",
    "blackstone_slab",
    "blackstone_stairs",
    "blackstone_wall",
    "blast_furnace",
    "blaze_powder",
    "blaze_rod",
    "blaze_spawn_egg",
    "bleach",
    "blue_candle",
    "blue_candle_cake",
    "blue_dye",
    "blue_glazed_terracotta",
    "blue_ice",
    "boat",
    "bone",
    "bone_block",
    "bone_meal",
    "book",
    "bookshelf",
    "border_block",
    "bordure_indented_banner_pattern",
    "bow",
    "bowl",
    "bread",
    "brewing_stand",
    "brewingstandblock",
    "brick",
    "brick_block",
    "brick_stairs",
    "brown_candle",
    "brown_candle_cake",
    "brown_dye",
    "brown_glazed_terracotta",
    "brown_mushroom",
    "brown_mushroom_block",
    "bubble_column",
    "bucket",
    "budding_amethyst",
    "cactus",
    "cake",
    "calcite",
    "camera",
    "campfire",
    "candle",
    "candle_cake",
    "carpet",
    "carrot",
    "carrot_on_a_stick",
    "carrots",
    "cartography_table",
    "carved_pumpkin",
    "cat_spawn_egg",
    "cauldron",
    "cave_spider_spawn_egg",
    "cave_vines",
    "cave_vines_body_with_berries",
    "cave_vines_head_with_berries",
    "chain",
    "chain_command_block",
    "chainmail_boots",
    "chainmail_chestplate",
    "chainmail_helmet",
    "chainmail_leggings",
    "charcoal",
    "chemical_heat",
    "chemistry_table",
    "chest",
    "chest_minecart",
    "chicken",
    "chicken_spawn_egg",
    "chiseled_deepslate",
    "chiseled_nether_bricks",
    "chiseled_polished_blackstone",
    "chorus_flower",
    "chorus_fruit",
    "chorus_plant",
    "clay",
    "clay_ball",
    "client_request_placeholder_block",
    "clock",
    "coal",
    "coal_block",
    "coal_ore",
    "cobbled_deepslate",
    "cobbled_deepslate_double_slab",
    "cobbled_deepslate_slab",
    "cobbled_deepslate_stairs",
    "cobbled_deepslate_wall",
    "cobblestone",
    "cobblestone_wall",
    "cocoa",
    "cocoa_beans",
    "cod",
    "cod_bucket",
    "cod_spawn_egg",
    "colored_torch_bp",
    "colored_torch_rg",
    "command_block",
    "command_block_minecart",
    "comparator",
    "compass",
    "composter",
    "compound",
    "concrete",
    "concrete_powder",
    "conduit",
    "cooked_beef",
    "cooked_chicken",
    "cooked_cod",
    "cooked_mutton",
    "cooked_porkchop",
    "cooked_rabbit",
    "cooked_salmon",
    "cookie",
    "copper_block",
    "copper_ingot",
    "copper_ore",
    "coral",
    "coral_block",
    "coral_fan",
    "coral_fan_dead",
    "coral_fan_hang",
    "coral_fan_hang2",
    "coral_fan_hang3",
    "cow_spawn_egg",
    "cracked_deepslate_bricks",
    "cracked_deepslate_tiles",
    "cracked_nether_bricks",
    "cracked_polished_blackstone_bricks",
    "crafting_table",
    "creeper_banner_pattern",
    "creeper_spawn_egg",
    "crimson_button",
    "crimson_door",
    "crimson_double_slab",
    "crimson_fence",
    "crimson_fence_gate",
    "crimson_fungus",
    "crimson_hyphae",
    "crimson_nylium",
    "crimson_planks",
    "crimson_pressure_plate",
    "crimson_roots",
    "crimson_sign",
    "crimson_slab",
    "crimson_stairs",
    "crimson_standing_sign",
    "crimson_stem",
    "crimson_trapdoor",
    "crimson_wall_sign",
    "crossbow",
    "crying_obsidian",
    "cut_copper",
    "cut_copper_slab",
    "cut_copper_stairs",
    "cyan_candle",
    "cyan_candle_cake",
    "cyan_dye",
    "cyan_glazed_terracotta",
    "dark_oak_boat",
    "dark_oak_button",
    "dark_oak_door",
    "dark_oak_fence_gate",
    "dark_oak_pressure_plate",
    "dark_oak_sign",
    "dark_oak_stairs",
    "dark_oak_trapdoor",
    "dark_prismarine_stairs",
    "darkoak_standing_sign",
    "darkoak_wall_sign",
    "daylight_detector",
    "daylight_detector_inverted",
    "deadbush",
    "debug_stick",
    "deepslate",
    "deepslate_brick_double_slab",
    "deepslate_brick_slab",
    "deepslate_brick_stairs",
    "deepslate_brick_wall",
    "deepslate_bricks",
    "deepslate_coal_ore",
    "deepslate_copper_ore",
    "deepslate_diamond_ore",
    "deepslate_emerald_ore",
    "deepslate_gold_ore",
    "deepslate_iron_ore",
    "deepslate_lapis_ore",
    "deepslate_redstone_ore",
    "deepslate_tile_double_slab",
    "deepslate_tile_slab",
    "deepslate_tile_stairs",
    "deepslate_tile_wall",
    "deepslate_tiles",
    "deny",
    "detector_rail",
    "diamond",
    "diamond_axe",
    "diamond_block",
    "diamond_boots",
    "diamond_chestplate",
    "diamond_helmet",
    "diamond_hoe",
    "diamond_horse_armor",
    "diamond_leggings",
    "diamond_ore",
    "diamond_pickaxe",
    "diamond_shovel",
    "diamond_sword",
    "diorite_stairs",
    "dirt",
    "dirt_with_roots",
    "dispenser",
    "dolphin_spawn_egg",
    "donkey_spawn_egg",
    "double_cut_copper_slab",
    "double_plant",
    "double_stone_slab",
    "double_stone_slab2",
    "double_stone_slab3",
    "double_stone_slab4",
    "double_wooden_slab",
    "dragon_breath",
    "dragon_egg",
    "dried_kelp",
    "dried_kelp_block",
    "dripstone_block",
    "dropper",
    "drowned_spawn_egg",
    "dye",
    "egg",
    "elder_guardian_spawn_egg",
    "element_0",
    "element_1",
    "element_10",
    "element_100",
    "element_101",
    "element_102",
    "element_103",
    "element_104",
    "element_105",
    "element_106",
    "element_107",
    "element_108",
    "element_109",
    "element_11",
    "element_110",
    "element_111",
    "element_112",
    "element_113",
    "element_114",
    "element_115",
    "element_116",
    "element_117",
    "element_118",
    "element_12",
    "element_13",
    "element_14",
    "element_15",
    "element_16",
    "element_17",
    "element_18",
    "element_19",
    "element_2",
    "element_20",
    "element_21",
    "element_22",
    "element_23",
    "element_24",
    "element_25",
    "element_26",
    "element_27",
    "element_28",
    "element_29",
    "element_3",
    "element_30",
    "element_31",
    "element_32",
    "element_33",
    "element_34",
    "element_35",
    "element_36",
    "element_37",
    "element_38",
    "element_39",
    "element_4",
    "element_40",
    "element_41",
    "element_42",
    "element_43",
    "element_44",
    "element_45",
    "element_46",
    "element_47",
    "element_48",
    "element_49",
    "element_5",
    "element_50",
    "element_51",
    "element_52",
    "element_53",
    "element_54",
    "element_55",
    "element_56",
    "element_57",
    "element_58",
    "element_59",
    "element_6",
    "element_60",
    "element_61",
    "element_62",
    "element_63",
    "element_64",
    "element_65",
    "element_66",
    "element_67",
    "element_68",
    "element_69",
    "element_7",
    "element_70",
    "element_71",
    "element_72",
    "element_73",
    "element_74",
    "element_75",
    "element_76",
    "element_77",
    "element_78",
    "element_79",
    "element_8",
    "element_80",
    "element_81",
    "element_82",
    "element_83",
    "element_84",
    "element_85",
    "element_86",
    "element_87",
    "element_88",
    "element_89",
    "element_9",
    "element_90",
    "element_91",
    "element_92",
    "element_93",
    "element_94",
    "element_95",
    "element_96",
    "element_97",
    "element_98",
    "element_99",
    "elytra",
    "emerald",
    "emerald_block",
    "emerald_ore",
    "empty_map",
    "enchanted_book",
    "enchanted_golden_apple",
    "enchanting_table",
    "end_brick_stairs",
    "end_bricks",
    "end_crystal",
    "end_gateway",
    "end_portal",
    "end_portal_frame",
    "end_rod",
    "end_stone",
    "ender_chest",
    "ender_eye",
    "ender_pearl",
    "enderman_spawn_egg",
    "endermite_spawn_egg",
    "evoker_spawn_egg",
    "experience_bottle",
    "exposed_copper",
    "exposed_cut_copper",
    "exposed_cut_copper_slab",
    "exposed_cut_copper_stairs",
    "exposed_double_cut_copper_slab",
    "farmland",
    "feather",
    "fence",
    "fence_gate",
    "fermented_spider_eye",
    "field_masoned_banner_pattern",
    "filled_map",
    "fire",
    "fire_charge",
    "firework_rocket",
    "firework_star",
    "fishing_rod",
    "fletching_table",
    "flint",
    "flint_and_steel",
    "flower_banner_pattern",
    "flower_pot",
    "flowering_azalea",
    "flowing_lava",
    "flowing_water",
    "fox_spawn_egg",
    "frame",
    "frosted_ice",
    "furnace",
    "ghast_spawn_egg",
    "ghast_tear",
    "gilded_blackstone",
    "glass",
    "glass_bottle",
    "glass_pane",
    "glistering_melon_slice",
    "glow_frame",
    "glow_ink_sac",
    "glow_lichen",
    "glow_squid_spawn_egg",
    "glow_stick",
    "glowingobsidian",
    "glowstone",
    "glowstone_dust",
    "goat_horn",
    "goat_spawn_egg",
    "gold_block",
    "gold_ingot",
    "gold_nugget",
    "gold_ore",
    "golden_apple",
    "golden_axe",
    "golden_boots",
    "golden_carrot",
    "golden_chestplate",
    "golden_helmet",
    "golden_hoe",
    "golden_horse_armor",
    "golden_leggings",
    "golden_pickaxe",
    "golden_rail",
    "golden_shovel",
    "golden_sword",
    "granite_stairs",
    "grass",
    "grass_path",
    "gravel",
    "gray_candle",
    "gray_candle_cake",
    "gray_dye",
    "gray_glazed_terracotta",
    "green_candle",
    "green_candle_cake",
    "green_dye",
    "green_glazed_terracotta",
    "grindstone",
    "guardian_spawn_egg",
    "gunpowder",
    "hanging_roots",
    "hard_glass",
    "hard_glass_pane",
    "hard_stained_glass",
    "hard_stained_glass_pane",
    "hardened_clay",
    "hay_block",
    "heart_of_the_sea",
    "heavy_weighted_pressure_plate",
    "hoglin_spawn_egg",
    "honey_block",
    "honey_bottle",
    "honeycomb",
    "honeycomb_block",
    "hopper",
    "hopper_minecart",
    "horse_spawn_egg",
    "husk_spawn_egg",
    "ice",
    "ice_bomb",
    "infested_deepslate",
    "info_update",
    "info_update2",
    "ink_sac",
    "invisiblebedrock",
    "iron_axe",
    "iron_bars",
    "iron_block",
    "iron_boots",
    "iron_chestplate",
    "iron_door",
    "iron_helmet",
    "iron_hoe",
    "iron_horse_armor",
    "iron_ingot",
    "iron_leggings",
    "iron_nugget",
    "iron_ore",
    "iron_pickaxe",
    "iron_shovel",
    "iron_sword",
    "iron_trapdoor",
    "item.acacia_door",
    "item.bed",
    "item.beetroot",
    "item.birch_door",
    "item.cake",
    "item.camera",
    "item.campfire",
    "item.cauldron",
    "item.chain",
    "item.crimson_door",
    "item.dark_oak_door",
    "item.flower_pot",
    "item.frame",
    "item.glow_frame",
    "item.hopper",
    "item.iron_door",
    "item.jungle_door",
    "item.kelp",
    "item.nether_sprouts",
    "item.nether_wart",
    "item.reeds",
    "item.skull",
    "item.soul_campfire",
    "item.spruce_door",
    "item.warped_door",
    "item.wheat",
    "item.wooden_door",
    "jigsaw",
    "jukebox",
    "jungle_boat",
    "jungle_button",
    "jungle_door",
    "jungle_fence_gate",
    "jungle_pressure_plate",
    "jungle_sign",
    "jungle_stairs",
    "jungle_standing_sign",
    "jungle_trapdoor",
    "jungle_wall_sign",
    "kelp",
    "ladder",
    "lantern",
    "lapis_block",
    "lapis_lazuli",
    "lapis_ore",
    "large_amethyst_bud",
    "lava",
    "lava_bucket",
    "lava_cauldron",
    "lead",
    "leather",
    "leather_boots",
    "leather_chestplate",
    "leather_helmet",
    "leather_horse_armor",
    "leather_leggings",
    "leaves",
    "leaves2",
    "lectern",
    "lever",
    "light_block",
    "light_blue_candle",
    "light_blue_candle_cake",
    "light_blue_dye",
    "light_blue_glazed_terracotta",
    "light_gray_candle",
    "light_gray_candle_cake",
    "light_gray_dye",
    "light_weighted_pressure_plate",
    "lightning_rod",
    "lime_candle",
    "lime_candle_cake",
    "lime_dye",
    "lime_glazed_terracotta",
    "lingering_potion",
    "lit_blast_furnace",
    "lit_deepslate_redstone_ore",
    "lit_furnace",
    "lit_pumpkin",
    "lit_redstone_lamp",
    "lit_redstone_ore",
    "lit_smoker",
    "llama_spawn_egg",
    "lodestone",
    "lodestone_compass",
    "log",
    "log2",
    "loom",
    "magenta_candle",
    "magenta_candle_cake",
    "magenta_dye",
    "magenta_glazed_terracotta",
    "magma",
    "magma_cream",
    "magma_cube_spawn_egg",
    "medicine",
    "medium_amethyst_bud",
    "melon_block",
    "melon_seeds",
    "melon_slice",
    "melon_stem",
    "milk_bucket",
    "minecart",
    "mob_spawner",
    "mojang_banner_pattern",
    "monster_egg",
    "mooshroom_spawn_egg",
    "moss_block",
    "moss_carpet",
    "mossy_cobblestone",
    "mossy_cobblestone_stairs",
    "mossy_stone_brick_stairs",
    "movingblock",
    "mule_spawn_egg",
    "mushroom_stew",
    "music_disc_11",
    "music_disc_13",
    "music_disc_blocks",
    "music_disc_cat",
    "music_disc_chirp",
    "music_disc_far",
    "music_disc_mall",
    "music_disc_mellohi",
    "music_disc_pigstep",
    "music_disc_stal",
    "music_disc_strad",
    "music_disc_wait",
    "music_disc_ward",
    "mutton",
    "mycelium",
    "mysterious_frame",
    "mysterious_frame_slot",
    "name_tag",
    "nautilus_shell",
    "nether_brick",
    "nether_brick_fence",
    "nether_brick_stairs",
    "nether_gold_ore",
    "nether_sprouts",
    "nether_star",
    "nether_wart",
    "nether_wart_block",
    "netherbrick",
    "netherite_axe",
    "netherite_block",
    "netherite_boots",
    "netherite_chestplate",
    "netherite_helmet",
    "netherite_hoe",
    "netherite_ingot",
    "netherite_leggings",
    "netherite_pickaxe",
    "netherite_scrap",
    "netherite_shovel",
    "netherite_sword",
    "netherrack",
    "netherreactor",
    "normal_stone_stairs",
    "noteblock",
    "npc_spawn_egg",
    "oak_boat",
    "oak_sign",
    "oak_stairs",
    "observer",
    "obsidian",
    "ocelot_spawn_egg",
    "orange_candle",
    "orange_candle_cake",
    "orange_dye",
    "orange_glazed_terracotta",
    "oxidized_copper",
    "oxidized_cut_copper",
    "oxidized_cut_copper_slab",
    "oxidized_cut_copper_stairs",
    "oxidized_double_cut_copper_slab",
    "packed_ice",
    "painting",
    "panda_spawn_egg",
    "paper",
    "parrot_spawn_egg",
    "phantom_membrane",
    "phantom_spawn_egg",
    "pig_spawn_egg",
    "piglin_banner_pattern",
    "piglin_brute_spawn_egg",
    "piglin_spawn_egg",
    "pillager_spawn_egg",
    "pink_candle",
    "pink_candle_cake",
    "pink_dye",
    "pink_glazed_terracotta",
    "piston",
    "pistonarmcollision",
    "planks",
    "podzol",
    "pointed_dripstone",
    "poisonous_potato",
    "polar_bear_spawn_egg",
    "polished_andesite_stairs",
    "polished_basalt",
    "polished_blackstone",
    "polished_blackstone_brick_double_slab",
    "polished_blackstone_brick_slab",
    "polished_blackstone_brick_stairs",
    "polished_blackstone_brick_wall",
    "polished_blackstone_bricks",
    "polished_blackstone_button",
    "polished_blackstone_double_slab",
    "polished_blackstone_pressure_plate",
    "polished_blackstone_slab",
    "polished_blackstone_stairs",
    "polished_blackstone_wall",
    "polished_deepslate",
    "polished_deepslate_double_slab",
    "polished_deepslate_slab",
    "polished_deepslate_stairs",
    "polished_deepslate_wall",
    "polished_diorite_stairs",
    "polished_granite_stairs",
    "popped_chorus_fruit",
    "porkchop",
    "portal",
    "potato",
    "potatoes",
    "potion",
    "powder_snow",
    "powder_snow_bucket",
    "powered_comparator",
    "powered_repeater",
    "prismarine",
    "prismarine_bricks_stairs",
    "prismarine_crystals",
    "prismarine_shard",
    "prismarine_stairs",
    "pufferfish",
    "pufferfish_bucket",
    "pufferfish_spawn_egg",
    "pumpkin",
    "pumpkin_pie",
    "pumpkin_seeds",
    "pumpkin_stem",
    "purple_candle",
    "purple_candle_cake",
    "purple_dye",
    "purple_glazed_terracotta",
    "purpur_block",
    "purpur_stairs",
    "quartz",
    "quartz_block",
    "quartz_bricks",
    "quartz_ore",
    "quartz_stairs",
    "rabbit",
    "rabbit_foot",
    "rabbit_hide",
    "rabbit_spawn_egg",
    "rabbit_stew",
    "rail",
    "rapid_fertilizer",
    "ravager_spawn_egg",
    "raw_copper",
    "raw_copper_block",
    "raw_gold",
    "raw_gold_block",
    "raw_iron",
    "raw_iron_block",
    "real_double_stone_slab",
    "real_double_stone_slab2",
    "real_double_stone_slab3",
    "real_double_stone_slab4",
    "red_candle",
    "red_candle_cake",
    "red_dye",
    "red_flower",
    "red_glazed_terracotta",
    "red_mushroom",
    "red_mushroom_block",
    "red_nether_brick",
    "red_nether_brick_stairs",
    "red_sandstone",
    "red_sandstone_stairs",
    "redstone",
    "redstone_block",
    "redstone_lamp",
    "redstone_ore",
    "redstone_torch",
    "redstone_wire",
    "repeater",
    "repeating_command_block",
    "reserved6",
    "respawn_anchor",
    "rotten_flesh",
    "saddle",
    "salmon",
    "salmon_bucket",
    "salmon_spawn_egg",
    "sand",
    "sandstone",
    "sandstone_stairs",
    "sapling",
    "scaffolding",
    "sculk",
    "sculk_catalyst",
    "sculk_sensor",
    "sculk_shrieker",
    "sculk_vein",
    "scute",
    "sea_pickle",
    "seagrass",
    "sealantern",
    "shears",
    "sheep_spawn_egg",
    "shield",
    "shroomlight",
    "shulker_box",
    "shulker_shell",
    "shulker_spawn_egg",
    "silver_glazed_terracotta",
    "silverfish_spawn_egg",
    "skeleton_horse_spawn_egg",
    "skeleton_spawn_egg",
    "skull",
    "skull_banner_pattern",
    "slime",
    "slime_ball",
    "slime_spawn_egg",
    "small_amethyst_bud",
    "small_dripleaf_block",
    "smithing_table",
    "smoker",
    "smooth_basalt",
    "smooth_quartz_stairs",
    "smooth_red_sandstone_stairs",
    "smooth_sandstone_stairs",
    "smooth_stone",
    "snow",
    "snow_layer",
    "snowball",
    "soul_campfire",
    "soul_fire",
    "soul_lantern",
    "soul_sand",
    "soul_soil",
    "soul_torch",
    "sparkler",
    "spawn_egg",
    "spider_eye",
    "spider_spawn_egg",
    "splash_potion",
    "sponge",
    "spore_blossom",
    "spruce_boat",
    "spruce_button",
    "spruce_door",
    "spruce_fence_gate",
    "spruce_pressure_plate",
    "spruce_sign",
    "spruce_stairs",
    "spruce_standing_sign",
    "spruce_trapdoor",
    "spruce_wall_sign",
    "spyglass",
    "squid_spawn_egg",
    "stained_glass",
    "stained_glass_pane",
    "stained_hardened_clay",
    "standing_banner",
    "standing_sign",
    "stick",
    "sticky_piston",
    "stickypistonarmcollision",
    "stone",
    "stone_axe",
    "stone_brick_stairs",
    "stone_button",
    "stone_hoe",
    "stone_pickaxe",
    "stone_pressure_plate",
    "stone_shovel",
    "stone_stairs",
    "stone_sword",
    "stonebrick",
    "stonecutter",
    "stonecutter_block",
    "stray_spawn_egg",
    "strider_spawn_egg",
    "string",
    "stripped_acacia_log",
    "stripped_birch_log",
    "stripped_crimson_hyphae",
    "stripped_crimson_stem",
    "stripped_dark_oak_log",
    "stripped_jungle_log",
    "stripped_oak_log",
    "stripped_spruce_log",
    "stripped_warped_hyphae",
    "stripped_warped_stem",
    "structure_block",
    "structure_void",
    "sugar",
    "sugar_cane",
    "suspicious_stew",
    "sweet_berries",
    "sweet_berry_bush",
    "tallgrass",
    "target",
    "tinted_glass",
    "tnt",
    "tnt_minecart",
    "torch",
    "totem_of_undying",
    "trapdoor",
    "trapped_chest",
    "trident",
    "tripwire",
    "tripwire_hook",
    "tropical_fish",
    "tropical_fish_bucket",
    "tropical_fish_spawn_egg",
    "tuff",
    "turtle_egg",
    "turtle_helmet",
    "turtle_spawn_egg",
    "twisting_vines",
    "underwater_torch",
    "undyed_shulker_box",
    "unknown",
    "unlit_redstone_torch",
    "unpowered_comparator",
    "unpowered_repeater",
    "vex_spawn_egg",
    "villager_spawn_egg",
    "vindicator_spawn_egg",
    "vine",
    "wall_banner",
    "wall_sign",
    "wandering_trader_spawn_egg",
    "warped_button",
    "warped_door",
    "warped_double_slab",
    "warped_fence",
    "warped_fence_gate",
    "warped_fungus",
    "warped_fungus_on_a_stick",
    "warped_hyphae",
    "warped_nylium",
    "warped_planks",
    "warped_pressure_plate",
    "warped_roots",
    "warped_sign",
    "warped_slab",
    "warped_stairs",
    "warped_standing_sign",
    "warped_stem",
    "warped_trapdoor",
    "warped_wall_sign",
    "warped_wart_block",
    "water",
    "water_bucket",
    "waterlily",
    "waxed_copper",
    "waxed_cut_copper",
    "waxed_cut_copper_slab",
    "waxed_cut_copper_stairs",
    "waxed_double_cut_copper_slab",
    "waxed_exposed_copper",
    "waxed_exposed_cut_copper",
    "waxed_exposed_cut_copper_slab",
    "waxed_exposed_cut_copper_stairs",
    "waxed_exposed_double_cut_copper_slab",
    "waxed_oxidized_copper",
    "waxed_oxidized_cut_copper",
    "waxed_oxidized_cut_copper_slab",
    "waxed_oxidized_cut_copper_stairs",
    "waxed_oxidized_double_cut_copper_slab",
    "waxed_weathered_copper",
    "waxed_weathered_cut_copper",
    "waxed_weathered_cut_copper_slab",
    "waxed_weathered_cut_copper_stairs",
    "waxed_weathered_double_cut_copper_slab",
    "weathered_copper",
    "weathered_cut_copper",
    "weathered_cut_copper_slab",
    "weathered_cut_copper_stairs",
    "weathered_double_cut_copper_slab",
    "web",
    "weeping_vines",
    "wheat",
    "wheat_seeds",
    "white_candle",
    "white_candle_cake",
    "white_dye",
    "white_glazed_terracotta",
    "witch_spawn_egg",
    "wither_rose",
    "wither_skeleton_spawn_egg",
    "wolf_spawn_egg",
    "wood",
    "wooden_axe",
    "wooden_button",
    "wooden_door",
    "wooden_hoe",
    "wooden_pickaxe",
    "wooden_pressure_plate",
    "wooden_shovel",
    "wooden_slab",
    "wooden_sword",
    "wool",
    "writable_book",
    "written_book",
    "yellow_candle",
    "yellow_candle_cake",
    "yellow_dye",
    "yellow_flower",
    "yellow_glazed_terracotta",
    "zoglin_spawn_egg",
    "zombie_horse_spawn_egg",
    "zombie_pigman_spawn_egg",
    "zombie_spawn_egg",
    "zombie_villager_spawn_egg",
]


















