# -*- coding: utf-8 -*-
# =================================================
#  ⠀
#   Copyright (c) 2025 Nuoyan
#  ⠀
#   Author: Nuoyan <https://github.com/charminglee>
#   Email : 1279735247@qq.com
#   Date  : 2025-12-19
#  ⠀
# =================================================


from typing import Literal, Union, Optional, Callable, Tuple
from mod.common.minecraftEnum import Facing
from ..core._types._typing import FTuple2, FTuple3, FTuple, ITuple, ITuple2


__Pos3OrEntityId = Union[FTuple3, str]
__PosOrEntityId = Union[FTuple, str]


_INF: float
_NAN: float
_ZERO_EPS: float
def _to_pos(target: __Pos3OrEntityId, is_client: Optional[bool] = None) -> FTuple3: ...
def _get_dim(entity_id: str) -> int: ...
def distance2nearest_entity(target: __Pos3OrEntityId, dim: Optional[int] = None) -> float: ...
def distance2nearest_player(target: __Pos3OrEntityId, dim: Optional[int] = None) -> float: ...
def distance2line(pos: __Pos3OrEntityId, line_pos1: FTuple3, line_pos2: FTuple3) -> float: ...
def distance_square(target1: __PosOrEntityId, target2: __PosOrEntityId) -> float: ...
def distance(target1: __PosOrEntityId, target2: __PosOrEntityId) -> float: ...
def chunk_pos(pos: FTuple3) -> Optional[ITuple2]: ...
def polar_coord(coord: FTuple2, rad: bool = False, origin: FTuple2 = (0, 0)) -> FTuple2: ...
def cartesian_coord(coord: FTuple2, rad: bool = False, origin: FTuple2 = (0, 0)) -> FTuple2: ...
def relative_pos(pos: FTuple, basis: FTuple) -> Optional[FTuple]: ...
def absolute_pos(pos: FTuple, basis: FTuple) -> Optional[FTuple]: ...
def screen_pos(
    pos: FTuple3,
    world_basis: FTuple3,
    screen_basis: FTuple2 = (0, 0),
    scale: float = 1,
    offset: FTuple2 = (0, 0),
    rotation: float = 0,
    rad: bool = False,
) -> Optional[FTuple2]: ...
def box_min_max(pos1: FTuple, pos2: FTuple) -> Optional[Tuple[FTuple, FTuple]]: ...
def pos_entity_facing(
    entity_id: str,
    dist: float,
    use_0yaw: bool = False,
    height_offset: float = 0,
) -> Optional[FTuple3]: ...
def pos_block_facing(pos: FTuple3, face: int = Facing.North, dist: float = 1.0) -> Optional[FTuple3]: ...
def pos_forward_rot(pos: FTuple3, rot: FTuple2, dist: float) -> Optional[FTuple3]: ...
def pos_floor(pos: FTuple) -> Optional[ITuple]: ...
def pos_rotate(pos: FTuple2, angle: float, basis: FTuple2 = (0, 0), rad: bool = False) -> Optional[FTuple2]: ...
def midpoint(pos1: FTuple, pos2: FTuple) -> Optional[FTuple]: ...
def box_center(pos1: FTuple, pos2: FTuple) -> Optional[FTuple]: ...
def ray_box_intersection(
    start_pos: FTuple3,
    ray_dir: FTuple3,
    length: float,
    aabb_center: FTuple3,
    aabb_size: FTuple3,
    handle_inside: Literal["none", "start", "exit"] = "none",
) -> Optional[FTuple3]: ...
def is_in_cylinder(target: __Pos3OrEntityId, r: float, center1: FTuple3, center2: FTuple3) -> bool: ...
def is_in_sector(target: __Pos3OrEntityId, r: float, h: float, angle: float, center: FTuple3, direction: FTuple3) -> bool: ...
def is_in_box(target: __PosOrEntityId, pos1: FTuple, pos2: FTuple, ignore_y: bool = False) -> bool: ...
def range_map(
    x: float,
    output_range: FTuple2,
    input_range: FTuple2 = [0, 1], # noqa
    func: Optional[Callable[[float], float]] = None,
) -> float: ...
def clamp(x: float, min_value: float, max_value: float) -> float: ...
def probability(p: float) -> bool: ...
def box_max_edge_len(pos1: FTuple, pos2: FTuple) -> float: ...
def camera_rot_p2p(pos1: FTuple3, pos2: FTuple3) -> Optional[FTuple2]: ...
