# -*- coding: utf-8 -*-
# =================================================
#  ⠀
#   Copyright (c) 2025 Nuoyan
#  ⠀
#   Author: Nuoyan <https://github.com/charminglee>
#   Email : 1279735247@qq.com
#   Date  : 2025-12-22
#  ⠀
# =================================================


from typing import List, Optional, Any, Iterable, Iterator, Callable, ClassVar, Literal, Union, overload, Dict
from ..core._types._typing import STuple, FTuple3, FTuple2, Self, VectorLike, Scalar, GeneralVector


_ZERO_EPS: float
VEC_ZERO: FTuple3
VEC_ONE: FTuple3
VEC_UP: FTuple3
VEC_DOWN: FTuple3
VEC_LEFT: FTuple3
VEC_RIGHT: FTuple3
VEC_FORWARD: FTuple3
VEC_BACKWARD: FTuple3
_OP_MAP = Dict[str, Callable[[Any, Any], Any]]


class Vector(object):
    __slots__: ClassVar[STuple]
    _x: float
    _y: float
    _z: float
    _dim: int
    @overload
    def __init__(self: Self, x: Scalar, y: Scalar, z: Scalar, /) -> None: ...
    @overload
    def __init__(self: Self, x: Scalar, y: Scalar, /) -> None: ...
    @overload
    def __init__(self: Self, x: Iterable[Scalar], /) -> None: ...
    @overload
    def __init__(self: Self) -> None: ...
    @staticmethod
    def zero(is_3d: bool = True) -> Vector: ...
    @staticmethod
    def one(is_3d: bool = True) -> Vector: ...
    @staticmethod
    def left(is_3d: bool = True) -> Vector: ...
    @staticmethod
    def right(is_3d: bool = True) -> Vector: ...
    @staticmethod
    def up(is_3d: bool = True) -> Vector: ...
    @staticmethod
    def down(is_3d: bool = True) -> Vector: ...
    @staticmethod
    def forward() -> Vector: ...
    @staticmethod
    def backward() -> Vector: ...
    @property
    def dim(self) -> int: ...
    @property
    def x(self) -> float: ...
    @x.setter
    def x(self, val: float) -> None: ...
    @property
    def y(self) -> float: ...
    @y.setter
    def y(self, val: float) -> None: ...
    @property
    def z(self) -> float: ...
    @z.setter
    def z(self, val: float) -> None: ...
    @property
    def xy(self) -> FTuple2: ...
    @property
    def xz(self) -> FTuple2: ...
    @property
    def yz(self) -> FTuple2: ...
    @property
    def xyz(self) -> FTuple3: ...
    @property
    def T(self) -> List[List[float]]: ...
    @property
    def length2(self) -> float: ...
    @property
    def length(self) -> float: ...
    @length.setter
    def length(self, val: float) -> None: ...
    def is_zero(self) -> bool: ...
    def normalize(self, inplace: bool = True) -> Vector: ...
    def __neg__(self) -> Vector: ...
    def neg(self, inplace: bool = True) -> Vector: ...
    def __eq__(self, other: Any) -> bool: ...
    def __ne__(self, other: Any) -> bool: ...
    def copy(self) -> Vector: ...
    __pos__ = __deepcopy__ = __copy__ = copy
    def __repr__(self) -> str: ...
    def __str__(self) -> str: ...
    def __getitem__(self, i: int) -> float: ...
    def __setitem__(self, i: int, value: Scalar) -> None: ...
    def __iter__(self) -> Iterator[float]: ...
    def __len__(self) -> int: ...
    def _op(
        self,
        other: Union[VectorLike, Scalar],
        operator: Literal["+", "-", "*", "/", "//"],
        scalar_only: bool = False,
    ) -> Vector: ...
    def _iop(
        self,
        other: Union[VectorLike, Scalar],
        operator: Literal["+", "-", "*", "/", "//"],
        scalar_only: bool = False,
    ) -> Vector: ...
    def __add__(self, other: Union[VectorLike, Scalar]) -> Vector: ...
    def __radd__(self, other: Union[VectorLike, Scalar]) -> Vector: ...
    def __iadd__(self, other: Union[VectorLike, Scalar]) -> Vector: ...
    def __sub__(self, other: Union[VectorLike, Scalar]) -> Vector: ...
    def __rsub__(self, other: Union[VectorLike, Scalar]) -> Vector: ...
    def __isub__(self, other: Union[VectorLike, Scalar]) -> Vector: ...
    def __mul__(self, other: Scalar) -> Vector: ...
    def __rmul__(self, other: Scalar) -> Vector: ...
    def __imul__(self, other: Scalar) -> Vector: ...
    def __truediv__(self, other: Scalar) -> Vector: ...
    def __itruediv__(self, other: Scalar) -> Vector: ...
    __div__ = __truediv__
    __idiv__ = __itruediv__
    def __floordiv__(self, other: Scalar) -> Vector: ...
    def __ifloordiv__(self, other: Scalar) -> Vector: ...
    def dot(self, vec: Optional[VectorLike] = None) -> float: ...
    def cross(self, vec: VectorLike, inplace: bool = True) -> Vector: ...
    def project(self, basis: VectorLike, inplace: bool = True) -> Vector: ...
    def project_length(self, basis: VectorLike) -> float: ...
    def angle_between(self, vec: VectorLike, ret_cos: bool = False, rad: bool = False) -> float: ...
    def rotate(self, angle: float, axis: Literal["x", "y", "z"], rad: bool = False, inplace: bool = True) -> Vector: ...
    def rotate_around(self, u: VectorLike, angle: float, rad: bool = False, inplace: bool = True) -> Vector: ...


def dir2rot(direction: FTuple3) -> Optional[FTuple2]: ...
def rot2dir(rot: FTuple2) -> Optional[FTuple3]: ...
def dir_from_to(start: VectorLike, end: VectorLike) -> GeneralVector: ...
def _is_scalar(val: Any) -> bool: ...
def vec_length2(vec: VectorLike) -> float: ...
def vec_length(vec: VectorLike) -> float: ...
def set_vec_length(vec: VectorLike, length: float) -> GeneralVector: ...
def vec_normalize(vec: VectorLike) -> GeneralVector: ...
def is_zero_vec(vec: VectorLike) -> bool: ...
def vec_neg(vec: VectorLike) -> GeneralVector: ...
def vec_add(vec: VectorLike, *more: Union[VectorLike, Scalar]) -> GeneralVector: ...
def vec_sub(vec: VectorLike, *more: Union[VectorLike, Scalar]) -> GeneralVector: ...
def vec_mul(vec: VectorLike, scalar: Scalar) -> GeneralVector: ...
def vec_div(vec: VectorLike, scalar: Scalar) -> GeneralVector: ...
def vec_dot(vec1: VectorLike, vec2: VectorLike) -> float: ...
def vec_cross(vec1: VectorLike, vec2: VectorLike) -> FTuple3: ...
def vec_project(vec: VectorLike, basis: VectorLike) -> GeneralVector: ...
def vec_project_length(vec: VectorLike, basis: VectorLike) -> float: ...
def vec_angle_between(vec1: VectorLike, vec2: VectorLike, rad: bool = False) -> float: ...
def vec_euler_rotate(
    vec: VectorLike,
    x_angle: float = 0.0,
    y_angle: float = 0.0,
    z_angle: float = 0.0,
    order: Literal["zyx", "zxy", "xyz", "xzy", "yxz", "yzx"] = "zyx",
    rad: bool = False,
) -> FTuple3: ...
def vec_rotate_around(v: VectorLike, u: VectorLike, angle: float, rad: bool = False) -> FTuple3: ...
def vec_entity_up(entity_id: str, ignore_rot_x: bool = False) -> Optional[FTuple3]: ...
def vec_entity_down(entity_id: str, ignore_rot_x: bool = False) -> Optional[FTuple3]: ...
def vec_entity_left(entity_id: str) -> Optional[FTuple3]: ...
def vec_entity_right(entity_id: str) -> Optional[FTuple3]: ...
def vec_entity_forward(entity_id: str, ignore_rot_x: bool = False) -> Optional[FTuple3]: ...
def vec_entity_backward(entity_id: str, ignore_rot_x: bool = False) -> Optional[FTuple3]: ...
def outgoing_vec(vec: VectorLike, normal: VectorLike) -> GeneralVector: ...
