# -*- coding: utf-8 -*-
# =================================================
#  ⠀
#   Copyright (c) 2026 Nuoyan
#  ⠀
#   Author: Nuoyan <https://github.com/charminglee>
#   Email : 1279735247@qq.com
#   Date  : 2026-2-10
#  ⠀
# =================================================


from typing import Any, Callable, Dict, List, Literal, Iterable, Optional, Union
from ..core._types._typing import Self, SlotsType, Args
from ..core._types._checker import args_type_check


__OpType = Literal["==", "!=", ">", "<", ">=", "<="]
__ConjoinOpType = Literal["&", "|"]


_OP_MAP: Dict[__OpType, Callable[[Any, Any], Any]]
def _eval_op(op: __OpType, this: Any, other: Any) -> bool: ...
def _eval_molang(entity_id: str, molang: str) -> Any: ...


class FilterFunc:
    @staticmethod
    def identifier(entity_id: str, op: __OpType, other: Any, *args: Any) -> bool: ...
    @staticmethod
    def health(entity_id: str, op: __OpType, other: Any, *args: Any) -> bool: ...
    @staticmethod
    def in_water(entity_id: str, op: __OpType, other: Any, *args: Any) -> bool: ...
    @staticmethod
    def in_lava(entity_id: str, op: __OpType, other: Any, *args: Any) -> bool: ...
    @staticmethod
    def on_fire(entity_id: str, op: __OpType, other: Any, *args: Any) -> bool: ...
    @staticmethod
    def family(entity_id: str, op: __OpType, other: Any, *args: Any) -> bool: ...
    @staticmethod
    def dimension(entity_id: str, op: __OpType, other: Any, *args: Any) -> bool: ...


class _FilterType(object):
    __slots__: SlotsType
    typ: List[str]
    args: List[Args]
    op: List[Optional[__OpType]]
    other: List[Optional[Any]]
    conjoin_op: List[__ConjoinOpType]
    def __init__(self: Self, typ: str, *args: Any) -> None: ...
    def __call__(self, entity_id: str) -> bool: ...
    def _set_comparison(self, op: __OpType, other: Any) -> None: ...
    def __eq__(self: Self, other: Any) -> Self: ...
    def __ne__(self: Self, other: Any) -> Self: ...
    def __gt__(self: Self, other: Any) -> Self: ...
    def __lt__(self: Self, other: Any) -> Self: ...
    def __ge__(self: Self, other: Any) -> Self: ...
    def __le__(self: Self, other: Any) -> Self: ...
    def _conjoin(self, op: __ConjoinOpType, ft: _FilterType) -> None: ...
    def __and__(self: Self, other: Any) -> Self: ...
    def __or__(self: Self, other: Any) -> Self: ...


class EntityFilter(object):
    entities: Iterable[str]
    def __init__(self: Self, entities: Iterable[str]) -> None: ...
    @args_type_check((_FilterType, callable))
    def __getitem__(self, key: Union[_FilterType, Callable[[str], bool]]) -> List[str]: ...
    @property
    def identifier(self) -> _FilterType: ...
    @property
    def health(self) -> _FilterType: ...
    @property
    def in_water(self) -> _FilterType: ...
    @property
    def in_lava(self) -> _FilterType: ...
    @property
    def on_fire(self) -> _FilterType: ...
    @property
    def family(self) -> _FilterType: ...
    @property
    def dimension(self) -> _FilterType: ...
